import type { Snippet } from "./types.js";

// Classic, well-known algorithms across languages. Rows are single-quoted so
// inner quotes stay literal; category is "algo".
const j = (...rows: string[]): string => rows.join("\n");

export const ALGORITHMS: Snippet[] = [
  // ---------------- TypeScript / JavaScript ----------------
  {
    id: "algo-fizzbuzz",
    language: "ts",
    category: "algo",
    difficulty: "easy",
    label: "FizzBuzz",
    description: "FizzBuzz（3でFizz・5でBuzz）",
    code: j(
      "for (let i = 1; i <= 100; i++) {",
      '  const fizz = i % 3 === 0 ? "Fizz" : "";',
      '  const buzz = i % 5 === 0 ? "Buzz" : "";',
      "  console.log(fizz + buzz || i);",
      "}",
    ),
  },
  {
    id: "algo-palindrome",
    language: "ts",
    category: "algo",
    difficulty: "easy",
    label: "Palindrome",
    description: "回文判定（前から読んでも後ろからでも同じ）",
    code: j(
      "const isPalindrome = (s: string): boolean =>",
      '  s === [...s].reverse().join("");',
    ),
  },
  {
    id: "algo-binsearch",
    language: "ts",
    category: "algo",
    difficulty: "medium",
    label: "Binary search",
    description: "二分探索（ソート済み配列から位置を求める）",
    code: j(
      "function binarySearch(xs: number[], t: number): number {",
      "  let lo = 0, hi = xs.length - 1;",
      "  while (lo <= hi) {",
      "    const mid = (lo + hi) >> 1;",
      "    if (xs[mid] === t) return mid;",
      "    if (xs[mid] < t) lo = mid + 1;",
      "    else hi = mid - 1;",
      "  }",
      "  return -1;",
      "}",
    ),
  },
  {
    id: "algo-twosum",
    language: "ts",
    category: "algo",
    difficulty: "medium",
    label: "Two Sum",
    description: "Two Sum（ハッシュで和が target になる2数）",
    code: j(
      "function twoSum(nums: number[], target: number) {",
      "  const seen = new Map<number, number>();",
      "  for (let i = 0; i < nums.length; i++) {",
      "    const need = target - nums[i];",
      "    if (seen.has(need)) return [seen.get(need), i];",
      "    seen.set(nums[i], i);",
      "  }",
      "}",
    ),
  },

  // ---------------- Python ----------------
  {
    id: "algo-fib",
    language: "py",
    category: "algo",
    difficulty: "easy",
    label: "Fibonacci",
    description: "フィボナッチ数列（反復）",
    code: j(
      "def fib(n):",
      "    a, b = 0, 1",
      "    for _ in range(n):",
      "        a, b = b, a + b",
      "    return a",
    ),
  },
  {
    id: "algo-quicksort",
    language: "py",
    category: "algo",
    difficulty: "hard",
    label: "Quicksort",
    description: "クイックソート（ピボットで分割して再帰）",
    code: j(
      "def quicksort(xs):",
      "    if len(xs) <= 1:",
      "        return xs",
      "    pivot, rest = xs[0], xs[1:]",
      "    left = [x for x in rest if x < pivot]",
      "    right = [x for x in rest if x >= pivot]",
      "    return quicksort(left) + [pivot] + quicksort(right)",
    ),
  },
  {
    id: "algo-sieve",
    language: "py",
    category: "algo",
    difficulty: "medium",
    label: "Sieve of Eratosthenes",
    description: "エラトステネスの篩（n以下の素数）",
    code: j(
      "def primes(n):",
      "    sieve = [True] * (n + 1)",
      "    for i in range(2, int(n ** 0.5) + 1):",
      "        if sieve[i]:",
      "            for j in range(i * i, n + 1, i):",
      "                sieve[j] = False",
      "    return [i for i in range(2, n + 1) if sieve[i]]",
    ),
  },
  {
    id: "algo-bfs",
    language: "py",
    category: "algo",
    difficulty: "hard",
    label: "Breadth-first search",
    description: "幅優先探索（BFS・キューで探索）",
    code: j(
      "def bfs(graph, start):",
      "    seen = {start}",
      "    queue = deque([start])",
      "    while queue:",
      "        node = queue.popleft()",
      "        for nxt in graph[node]:",
      "            if nxt not in seen:",
      "                seen.add(nxt)",
      "                queue.append(nxt)",
      "    return seen",
    ),
  },

  // ---------------- Go ----------------
  {
    id: "algo-gcd",
    language: "go",
    category: "algo",
    difficulty: "easy",
    label: "GCD (Euclid)",
    description: "最大公約数（ユークリッドの互除法）",
    code: j("func gcd(a, b int) int {", "  for b != 0 {", "    a, b = b, a%b", "  }", "  return a", "}"),
  },
  {
    id: "algo-bubble",
    language: "go",
    category: "algo",
    difficulty: "medium",
    label: "Bubble sort",
    description: "バブルソート（隣り合う要素を交換）",
    code: j(
      "func bubbleSort(xs []int) {",
      "  for i := 0; i < len(xs); i++ {",
      "    for j := 0; j < len(xs)-i-1; j++ {",
      "      if xs[j] > xs[j+1] {",
      "        xs[j], xs[j+1] = xs[j+1], xs[j]",
      "      }",
      "    }",
      "  }",
      "}",
    ),
  },

  // ---------------- Rust ----------------
  {
    id: "algo-factorial",
    language: "rust",
    category: "algo",
    difficulty: "easy",
    label: "Factorial",
    description: "階乗（範囲の積をとる）",
    code: j("fn factorial(n: u64) -> u64 {", "  (1..=n).product()", "}"),
  },
  {
    id: "algo-fib-fold",
    language: "rust",
    category: "algo",
    difficulty: "medium",
    label: "Fibonacci (fold)",
    description: "フィボナッチ（fold で畳み込み）",
    code: j(
      "fn fib(n: u32) -> u64 {",
      "  (0..n).fold((0u64, 1u64), |(a, b), _| (b, a + b)).0",
      "}",
    ),
  },

  // ---------------- Dynamic programming ----------------
  {
    id: "algo-climb",
    language: "ts",
    category: "algo",
    difficulty: "medium",
    label: "Climbing stairs",
    description: "階段の上り方の総数（DP・フィボナッチ的）",
    code: j(
      "function climbStairs(n: number): number {",
      "  let [a, b] = [1, 1];",
      "  for (let i = 0; i < n; i++) [a, b] = [b, a + b];",
      "  return a;",
      "}",
    ),
  },
  {
    id: "algo-coins",
    language: "py",
    category: "algo",
    difficulty: "hard",
    label: "Coin change",
    description: "コイン問題（DPで最小枚数を求める）",
    code: j(
      "def coin_change(coins, amount):",
      '    dp = [0] + [float("inf")] * amount',
      "    for c in coins:",
      "        for x in range(c, amount + 1):",
      "            dp[x] = min(dp[x], dp[x - c] + 1)",
      "    return dp[amount]",
    ),
  },
  {
    id: "algo-anagram",
    language: "py",
    category: "algo",
    difficulty: "easy",
    label: "Anagram check",
    description: "アナグラム判定（文字を並べ替えて一致）",
    code: j("def is_anagram(a, b):", "    return sorted(a) == sorted(b)"),
  },
  {
    id: "algo-kadane",
    language: "ts",
    category: "algo",
    difficulty: "hard",
    label: "Kadane (max subarray)",
    description: "最大部分和（Kadane のアルゴリズム）",
    code: j(
      "function maxSubarray(xs: number[]): number {",
      "  let best = xs[0], cur = xs[0];",
      "  for (let i = 1; i < xs.length; i++) {",
      "    cur = Math.max(xs[i], cur + xs[i]);",
      "    best = Math.max(best, cur);",
      "  }",
      "  return best;",
      "}",
    ),
  },
  {
    id: "algo-valid-parens",
    language: "ts",
    category: "algo",
    difficulty: "medium",
    label: "Valid parentheses",
    description: "括弧の対応をスタックで検証",
    code: j(
      "function isValid(s: string): boolean {",
      '  const pairs: Record<string, string> = { ")": "(", "]": "[", "}": "{" };',
      "  const stack: string[] = [];",
      "  for (const c of s) {",
      "    if (c in pairs) {",
      "      if (stack.pop() !== pairs[c]) return false;",
      "    } else {",
      "      stack.push(c);",
      "    }",
      "  }",
      "  return stack.length === 0;",
      "}",
    ),
  },
  {
    id: "algo-dfs",
    language: "py",
    category: "algo",
    difficulty: "hard",
    label: "Depth-first search",
    description: "深さ優先探索（DFS・再帰）",
    code: j(
      "def dfs(graph, node, seen):",
      "    seen.add(node)",
      "    for nxt in graph[node]:",
      "        if nxt not in seen:",
      "            dfs(graph, nxt, seen)",
    ),
  },

  // ---------------- More languages ----------------
  {
    id: "algo-prime",
    language: "go",
    category: "algo",
    difficulty: "medium",
    label: "Primality test",
    description: "素数判定（平方根までの試し割り）",
    code: j(
      "func isPrime(n int) bool {",
      "  if n < 2 {",
      "    return false",
      "  }",
      "  for i := 2; i*i <= n; i++ {",
      "    if n%i == 0 {",
      "      return false",
      "    }",
      "  }",
      "  return true",
      "}",
    ),
  },
  {
    id: "algo-insertion-sort",
    language: "java",
    category: "algo",
    difficulty: "hard",
    label: "Insertion sort",
    description: "挿入ソート（整列済みの部分に挿し込む）",
    code: j(
      "static void insertionSort(int[] a) {",
      "  for (int i = 1; i < a.length; i++) {",
      "    int key = a[i];",
      "    int j = i - 1;",
      "    while (j >= 0 && a[j] > key) {",
      "      a[j + 1] = a[j];",
      "      j--;",
      "    }",
      "    a[j + 1] = key;",
      "  }",
      "}",
    ),
  },
  {
    id: "algo-popcount",
    language: "cpp",
    category: "algo",
    difficulty: "medium",
    label: "Popcount (Kernighan)",
    description: "立っているビットの数（最下位の1を消していく）",
    code: j(
      "int popcount(unsigned n) {",
      "  int bits = 0;",
      "  while (n) {",
      "    n &= n - 1;",
      "    bits++;",
      "  }",
      "  return bits;",
      "}",
    ),
  },
  {
    id: "algo-leap-year",
    language: "csharp",
    category: "algo",
    difficulty: "easy",
    label: "Leap year",
    description: "うるう年の判定（4・100・400 の規則）",
    code: j(
      "static bool IsLeapYear(int y) =>",
      "  y % 4 == 0 && (y % 100 != 0 || y % 400 == 0);",
    ),
  },
  {
    id: "algo-merge-sorted",
    language: "swift",
    category: "algo",
    difficulty: "hard",
    label: "Merge sorted arrays",
    description: "整列済みの2配列を1つにマージする",
    code: j(
      "func merge(_ a: [Int], _ b: [Int]) -> [Int] {",
      "  var (i, j, out) = (0, 0, [Int]())",
      "  while i < a.count && j < b.count {",
      "    if a[i] <= b[j] {",
      "      out.append(a[i])",
      "      i += 1",
      "    } else {",
      "      out.append(b[j])",
      "      j += 1",
      "    }",
      "  }",
      "  return out + a[i...] + b[j...]",
      "}",
    ),
  },
  {
    id: "algo-hamming",
    language: "kotlin",
    category: "algo",
    difficulty: "medium",
    label: "Hamming distance",
    description: "ハミング距離（異なる位置の数を数える）",
    code: j(
      "fun hamming(a: String, b: String) =",
      "  a.zip(b).count { (x, y) -> x != y }",
    ),
  },
  {
    id: "algo-collatz",
    language: "ruby",
    category: "algo",
    difficulty: "medium",
    label: "Collatz steps",
    description: "コラッツ数列が 1 になるまでの手数",
    code: j(
      "def collatz(n)",
      "  steps = 0",
      "  until n == 1",
      "    n = n.even? ? n / 2 : 3 * n + 1",
      "    steps += 1",
      "  end",
      "  steps",
      "end",
    ),
  },
  {
    id: "algo-power-of-two",
    language: "php",
    category: "algo",
    difficulty: "medium",
    label: "Power of two",
    description: "2 のべき乗かをビット演算で判定する",
    code: j(
      "function isPowerOfTwo(int $n): bool {",
      "  return $n > 0 && ($n & ($n - 1)) === 0;",
      "}",
    ),
  },
  {
    id: "algo-str-reverse",
    language: "c",
    category: "algo",
    difficulty: "medium",
    label: "Reverse string",
    description: "文字列をその場で反転する（両端から交換）",
    code: j(
      "void reverse(char *s) {",
      "  size_t n = strlen(s);",
      "  for (size_t i = 0; i < n / 2; i++) {",
      "    char tmp = s[i];",
      "    s[i] = s[n - 1 - i];",
      "    s[n - 1 - i] = tmp;",
      "  }",
      "}",
    ),
  },
  {
    id: "algo-list-reverse",
    language: "c",
    category: "algo",
    difficulty: "hard",
    label: "Reverse linked list",
    description: "連結リストを反転する（ポインタの付け替え）",
    code: j(
      "struct Node *reverse(struct Node *head) {",
      "  struct Node *prev = NULL;",
      "  while (head != NULL) {",
      "    struct Node *next = head->next;",
      "    head->next = prev;",
      "    prev = head;",
      "    head = next;",
      "  }",
      "  return prev;",
      "}",
    ),
  },
  {
    id: "algo-selection-sort",
    language: "zig",
    category: "algo",
    difficulty: "medium",
    label: "Selection sort",
    description: "選択ソート（残りから最小を選んで先頭と交換）",
    code: j(
      "fn selectionSort(items: []i32) void {",
      "    for (0..items.len) |i| {",
      "        var smallest = i;",
      "        for (i + 1..items.len) |j| {",
      "            if (items[j] < items[smallest]) smallest = j;",
      "        }",
      "        std.mem.swap(i32, &items[i], &items[smallest]);",
      "    }",
      "}",
    ),
  },
  {
    id: "algo-fast-power",
    language: "dart",
    category: "algo",
    difficulty: "medium",
    label: "Fast power",
    description: "繰り返し二乗法（指数を半分にしながら掛ける）",
    code: j(
      "int power(int base, int exponent) {",
      "  var result = 1;",
      "  var square = base;",
      "  for (var e = exponent; e > 0; e >>= 1) {",
      "    if (e.isOdd) result *= square;",
      "    square *= square;",
      "  }",
      "  return result;",
      "}",
    ),
  },
  {
    id: "algo-merge-sort",
    language: "scala",
    category: "algo",
    difficulty: "hard",
    label: "Merge sort",
    description: "マージソート（半分に分けて再帰し、併合する）",
    code: j(
      "def mergeSort(xs: List[Int]): List[Int] =",
      "  def merge(a: List[Int], b: List[Int]): List[Int] = (a, b) match",
      "    case (Nil, _) => b",
      "    case (_, Nil) => a",
      "    case (x :: xt, y :: _) if x <= y => x :: merge(xt, b)",
      "    case (_, y :: yt) => y :: merge(a, yt)",
      "  if xs.length <= 1 then xs",
      "  else",
      "    val (left, right) = xs.splitAt(xs.length / 2)",
      "    merge(mergeSort(left), mergeSort(right))",
    ),
  },
];
