import type { Snippet } from "./types.js";

// Classic, well-known algorithms across languages. Rows are single-quoted so
// inner quotes stay literal; category is "algo".
const j = (...rows: string[]): string => rows.join("\n");

export const ALGORITHMS: Snippet[] = [
  // ---------------- TypeScript / JavaScript ----------------
  {
    id: "algo-fizzbuzz",
    language: "ts",
    category: "algo",
    difficulty: "easy",
    label: "FizzBuzz",
    description: "FizzBuzz（3でFizz・5でBuzz）",
    code: j(
      "for (let i = 1; i <= 100; i++) {",
      '  const fizz = i % 3 === 0 ? "Fizz" : "";',
      '  const buzz = i % 5 === 0 ? "Buzz" : "";',
      "  console.log(fizz + buzz || i);",
      "}",
    ),
  },
  {
    id: "algo-palindrome",
    language: "ts",
    category: "algo",
    difficulty: "easy",
    label: "Palindrome",
    description: "回文判定（前から読んでも後ろからでも同じ）",
    code: j(
      "const isPalindrome = (s: string): boolean =>",
      '  s === [...s].reverse().join("");',
    ),
  },
  {
    id: "algo-binsearch",
    language: "ts",
    category: "algo",
    difficulty: "medium",
    label: "Binary search",
    description: "二分探索（ソート済み配列から位置を求める）",
    code: j(
      "function binarySearch(xs: number[], t: number): number {",
      "  let lo = 0, hi = xs.length - 1;",
      "  while (lo <= hi) {",
      "    const mid = (lo + hi) >> 1;",
      "    if (xs[mid] === t) return mid;",
      "    if (xs[mid] < t) lo = mid + 1;",
      "    else hi = mid - 1;",
      "  }",
      "  return -1;",
      "}",
    ),
  },
  {
    id: "algo-twosum",
    language: "ts",
    category: "algo",
    difficulty: "medium",
    label: "Two Sum",
    description: "Two Sum（ハッシュで和が target になる2数）",
    code: j(
      "function twoSum(nums: number[], target: number) {",
      "  const seen = new Map<number, number>();",
      "  for (let i = 0; i < nums.length; i++) {",
      "    const need = target - nums[i];",
      "    if (seen.has(need)) return [seen.get(need), i];",
      "    seen.set(nums[i], i);",
      "  }",
      "}",
    ),
  },

  // ---------------- Python ----------------
  {
    id: "algo-fib",
    language: "py",
    category: "algo",
    difficulty: "easy",
    label: "Fibonacci",
    description: "フィボナッチ数列（反復）",
    code: j(
      "def fib(n):",
      "    a, b = 0, 1",
      "    for _ in range(n):",
      "        a, b = b, a + b",
      "    return a",
    ),
  },
  {
    id: "algo-quicksort",
    language: "py",
    category: "algo",
    difficulty: "hard",
    label: "Quicksort",
    description: "クイックソート（ピボットで分割して再帰）",
    code: j(
      "def quicksort(xs):",
      "    if len(xs) <= 1:",
      "        return xs",
      "    pivot, rest = xs[0], xs[1:]",
      "    left = [x for x in rest if x < pivot]",
      "    right = [x for x in rest if x >= pivot]",
      "    return quicksort(left) + [pivot] + quicksort(right)",
    ),
  },
  {
    id: "algo-sieve",
    language: "py",
    category: "algo",
    difficulty: "medium",
    label: "Sieve of Eratosthenes",
    description: "エラトステネスの篩（n以下の素数）",
    code: j(
      "def primes(n):",
      "    sieve = [True] * (n + 1)",
      "    for i in range(2, int(n ** 0.5) + 1):",
      "        if sieve[i]:",
      "            for j in range(i * i, n + 1, i):",
      "                sieve[j] = False",
      "    return [i for i in range(2, n + 1) if sieve[i]]",
    ),
  },
  {
    id: "algo-bfs",
    language: "py",
    category: "algo",
    difficulty: "hard",
    label: "Breadth-first search",
    description: "幅優先探索（BFS・キューで探索）",
    code: j(
      "def bfs(graph, start):",
      "    seen = {start}",
      "    queue = deque([start])",
      "    while queue:",
      "        node = queue.popleft()",
      "        for nxt in graph[node]:",
      "            if nxt not in seen:",
      "                seen.add(nxt)",
      "                queue.append(nxt)",
      "    return seen",
    ),
  },

  // ---------------- Go ----------------
  {
    id: "algo-gcd",
    language: "go",
    category: "algo",
    difficulty: "easy",
    label: "GCD (Euclid)",
    description: "最大公約数（ユークリッドの互除法）",
    code: j("func gcd(a, b int) int {", "  for b != 0 {", "    a, b = b, a%b", "  }", "  return a", "}"),
  },
  {
    id: "algo-bubble",
    language: "go",
    category: "algo",
    difficulty: "medium",
    label: "Bubble sort",
    description: "バブルソート（隣り合う要素を交換）",
    code: j(
      "func bubbleSort(xs []int) {",
      "  for i := 0; i < len(xs); i++ {",
      "    for j := 0; j < len(xs)-i-1; j++ {",
      "      if xs[j] > xs[j+1] {",
      "        xs[j], xs[j+1] = xs[j+1], xs[j]",
      "      }",
      "    }",
      "  }",
      "}",
    ),
  },

  // ---------------- Rust ----------------
  {
    id: "algo-factorial",
    language: "rust",
    category: "algo",
    difficulty: "easy",
    label: "Factorial",
    description: "階乗（範囲の積をとる）",
    code: j("fn factorial(n: u64) -> u64 {", "  (1..=n).product()", "}"),
  },
  {
    id: "algo-fib-fold",
    language: "rust",
    category: "algo",
    difficulty: "medium",
    label: "Fibonacci (fold)",
    description: "フィボナッチ（fold で畳み込み）",
    code: j(
      "fn fib(n: u32) -> u64 {",
      "  (0..n).fold((0u64, 1u64), |(a, b), _| (b, a + b)).0",
      "}",
    ),
  },

  // ---------------- Dynamic programming ----------------
  {
    id: "algo-climb",
    language: "ts",
    category: "algo",
    difficulty: "medium",
    label: "Climbing stairs",
    description: "階段の上り方の総数（DP・フィボナッチ的）",
    code: j(
      "function climbStairs(n: number): number {",
      "  let [a, b] = [1, 1];",
      "  for (let i = 0; i < n; i++) [a, b] = [b, a + b];",
      "  return a;",
      "}",
    ),
  },
  {
    id: "algo-coins",
    language: "py",
    category: "algo",
    difficulty: "hard",
    label: "Coin change",
    description: "コイン問題（DPで最小枚数を求める）",
    code: j(
      "def coin_change(coins, amount):",
      '    dp = [0] + [float("inf")] * amount',
      "    for c in coins:",
      "        for x in range(c, amount + 1):",
      "            dp[x] = min(dp[x], dp[x - c] + 1)",
      "    return dp[amount]",
    ),
  },
];
