import type { Snippet } from "./types.js";

// Symbol / operator drills: single-line repetition of the punctuation that
// trips up code typing. Language is "drill", category "drill".
export const DRILLS: Snippet[] = [
  {
    id: "drill-arrows",
    language: "drill",
    category: "drill",
    difficulty: "easy",
    label: "Arrows",
    description: "アロー演算子 => -> の反復練習",
    code: "=> -> => -> => -> => -> => ->",
  },
  {
    id: "drill-compare",
    language: "drill",
    category: "drill",
    difficulty: "easy",
    label: "Comparison",
    description: "比較演算子の反復練習",
    code: "=== !== == != <= >= === !== <= >=",
  },
  {
    id: "drill-logic",
    language: "drill",
    category: "drill",
    difficulty: "medium",
    label: "Logic / optional",
    description: "論理・オプショナル演算子の反復練習",
    code: "&& || ?? ?. && || ?? ?. && ||",
  },
  {
    id: "drill-brackets",
    language: "drill",
    category: "drill",
    difficulty: "medium",
    label: "Brackets",
    description: "各種カッコの組み合わせ練習",
    code: "{} [] () <> {[()]} <[]> ({[]}) []",
  },
  {
    id: "drill-assign",
    language: "drill",
    category: "drill",
    difficulty: "medium",
    label: "Compound assign",
    description: "複合代入演算子の反復練習",
    code: "+= -= *= /= %= **= ||= &&= ??=",
  },
  {
    id: "drill-symbols",
    language: "drill",
    category: "drill",
    difficulty: "hard",
    label: "Punctuation",
    description: "記号キーの反復練習",
    code: "~ ! @ # $ % ^ & * - _ + = | : ;",
  },
  {
    id: "drill-pipes",
    language: "drill",
    category: "drill",
    difficulty: "hard",
    label: "Pipes / paths",
    description: "パイプ・パス系記号の反復練習",
    code: "|> >> << :: -> => |> >> :: ->",
  },
  {
    id: "drill-increment",
    language: "drill",
    category: "drill",
    difficulty: "easy",
    label: "Increment",
    description: "インクリメント・デクリメントの反復練習",
    code: "i++ j-- ++i --j i++ j-- ++i --j i++ j--",
  },
  {
    id: "drill-naming",
    language: "drill",
    category: "drill",
    difficulty: "easy",
    label: "Naming cases",
    description: "camelCase / snake_case / PascalCase / kebab-case の練習",
    code: "camelCase snake_case PascalCase kebab-case SCREAMING_SNAKE",
  },
  {
    id: "drill-numbers",
    language: "drill",
    category: "drill",
    difficulty: "medium",
    label: "Number literals",
    description: "16進・2進・指数・色コードなど数値リテラルの練習",
    code: "0xff 0b1010 1e-9 3.14 1_000_000 0o755 #5cf2ff 42",
  },
  {
    id: "drill-quotes",
    language: "drill",
    category: "drill",
    difficulty: "medium",
    label: "Quotes",
    description: "各種クォートとエスケープの練習",
    code: "\"a\" 'b' `c` \"\" '' `` \"${x}\" '\\n' `${y}`",
  },
  {
    id: "drill-generics",
    language: "drill",
    category: "drill",
    difficulty: "hard",
    label: "Generics",
    description: "山カッコを使う型表記の練習",
    code: "<T> Vec<T> Map<K, V> Option<&str> T[] Array<[K, V]>",
  },
  {
    id: "drill-regex",
    language: "drill",
    category: "drill",
    difficulty: "hard",
    label: "Regex",
    description: "正規表現でよく使う記号の練習",
    code: "^\\d{3}-\\d{4}$ [a-z]+ (foo|bar)? \\w+@\\w+\\.\\w+ .*?",
  },
];
