import type { Snippet } from "./types.js";

// Join rows into a single `\n`-delimited string. Rows are written as
// single-quoted strings so inner backticks and ${...} stay literal.
const j = (...rows: string[]): string => rows.join("\n");

export const CODE_SNIPPETS: Snippet[] = [
  // ---------------- TypeScript / JavaScript ----------------
  {
    id: "ts-const",
    language: "ts",
    category: "basics",
    difficulty: "easy",
    label: "const & log",
    description: "文字列を定数に入れてコンソール出力する",
    code: j('const greeting = "hello, world";', "console.log(greeting);"),
  },
  {
    id: "ts-ternary",
    language: "ts",
    category: "flow",
    difficulty: "easy",
    label: "Ternary",
    description: "三項演算子で条件によって値を選ぶ",
    code: j('const label = ok ? "yes" : "no";'),
  },
  {
    id: "ts-arrow",
    language: "ts",
    category: "functions",
    difficulty: "easy",
    label: "Arrow fn",
    description: "2つの数値を受け取り和を返すアロー関数",
    code: j("const sum = (a: number, b: number): number => a + b;"),
  },
  {
    id: "ts-chain",
    language: "ts",
    category: "functions",
    difficulty: "medium",
    label: "filter / map",
    description: "偶数だけ絞り込んで2倍にするメソッドチェーン",
    code: j(
      "const doubled = nums",
      "  .filter((n) => n % 2 === 0)",
      "  .map((n) => n * 2);",
    ),
  },
  {
    id: "ts-interface",
    language: "ts",
    category: "basics",
    difficulty: "medium",
    label: "Interface",
    description: "オブジェクトの形を表す interface 定義",
    code: j(
      "interface User {",
      "  id: number;",
      "  name: string;",
      "  active?: boolean;",
      "}",
    ),
  },
  {
    id: "ts-async",
    language: "ts",
    category: "async",
    difficulty: "medium",
    label: "async / await",
    description: "URL を非同期に取得して JSON を返す",
    code: j(
      "async function load(url: string) {",
      "  const res = await fetch(url);",
      "  return res.json();",
      "}",
    ),
  },
  {
    id: "ts-guard",
    language: "ts",
    category: "flow",
    difficulty: "hard",
    label: "Guard clause",
    description: "権限を判定して許可するか例外を投げる",
    code: j(
      'if (user?.role === "admin" && !user.banned) {',
      "  grantAccess();",
      "} else {",
      '  throw new Error("denied");',
      "}",
    ),
  },
  {
    id: "ts-react",
    language: "ts",
    category: "functions",
    difficulty: "hard",
    label: "React hooks",
    description: "state とドキュメントタイトルを同期する hooks",
    code: j(
      "const [count, setCount] = useState(0);",
      "useEffect(() => {",
      "  document.title = `count: ${count}`;",
      "}, [count]);",
    ),
  },

  // ---------------- Python ----------------
  {
    id: "py-print",
    language: "py",
    category: "basics",
    difficulty: "easy",
    label: "print",
    description: "文字列を標準出力する",
    code: j('print("hello, world")'),
  },
  {
    id: "py-fstring",
    language: "py",
    category: "basics",
    difficulty: "easy",
    label: "f-string",
    description: "f-string で変数を埋め込んで出力する",
    code: j('name = "Ada"', 'print(f"hello, {name}!")'),
  },
  {
    id: "py-def",
    language: "py",
    category: "functions",
    difficulty: "easy",
    label: "def",
    description: "2つの引数を足して返す関数定義",
    code: j("def add(a, b):", "    return a + b"),
  },
  {
    id: "py-comp",
    language: "py",
    category: "functions",
    difficulty: "medium",
    label: "Comprehension",
    description: "内包表記で偶数の二乗リストを作る",
    code: j("squares = [x * x for x in range(10) if x % 2 == 0]"),
  },
  {
    id: "py-dict",
    language: "py",
    category: "basics",
    difficulty: "medium",
    label: "Dict literal",
    description: "辞書リテラルで設定値をまとめる",
    code: j("config = {", '    "debug": True,', '    "retries": 3,', "}"),
  },
  {
    id: "py-with",
    language: "py",
    category: "flow",
    difficulty: "medium",
    label: "with / for",
    description: "ファイルを開いて1行ずつ処理する",
    code: j(
      'with open("data.txt") as f:',
      "    for line in f:",
      "        print(line.strip())",
    ),
  },
  {
    id: "py-try",
    language: "py",
    category: "flow",
    difficulty: "hard",
    label: "try / except",
    description: "例外を捕まえて既定値にフォールバックする",
    code: j(
      "try:",
      "    value = int(raw)",
      "except ValueError:",
      "    value = 0",
    ),
  },
  {
    id: "py-decorator",
    language: "py",
    category: "functions",
    difficulty: "hard",
    label: "Decorator",
    description: "デコレータで URL ルーティングを定義する",
    code: j(
      '@app.route("/users/<int:id>")',
      "def get_user(id):",
      "    return jsonify(db.get(id))",
    ),
  },

  // ---------------- Go ----------------
  {
    id: "go-hello",
    language: "go",
    category: "basics",
    difficulty: "easy",
    label: "Println",
    description: "標準出力に文字列を表示する",
    code: j('fmt.Println("hello, world")'),
  },
  {
    id: "go-func",
    language: "go",
    category: "functions",
    difficulty: "easy",
    label: "func",
    description: "2つの整数を足して返す関数",
    code: j("func add(a, b int) int {", "  return a + b", "}"),
  },
  {
    id: "go-struct",
    language: "go",
    category: "basics",
    difficulty: "medium",
    label: "struct",
    description: "座標を表す構造体の定義",
    code: j("type Point struct {", "  X int", "  Y int", "}"),
  },
  {
    id: "go-range",
    language: "go",
    category: "functions",
    difficulty: "medium",
    label: "for range",
    description: "スライスを range で添字付きに反復する",
    code: j(
      "nums := []int{1, 2, 3, 4}",
      "for i, n := range nums {",
      '  fmt.Printf("%d: %d\\n", i, n)',
      "}",
    ),
  },
  {
    id: "go-err",
    language: "go",
    category: "flow",
    difficulty: "hard",
    label: "if err != nil",
    description: "ファイル読込のエラーを早期 return する",
    code: j(
      "data, err := os.ReadFile(path)",
      "if err != nil {",
      "  return nil, err",
      "}",
    ),
  },
  {
    id: "go-goroutine",
    language: "go",
    category: "async",
    difficulty: "hard",
    label: "goroutine",
    description: "goroutine で計算しチャネルで受け取る",
    code: j("go func() {", "  ch <- compute()", "}()", "result := <-ch"),
  },

  // ---------------- Rust ----------------
  {
    id: "rust-hello",
    language: "rust",
    category: "basics",
    difficulty: "easy",
    label: "println!",
    description: "マクロで文字列を表示する",
    code: j('println!("hello, world");'),
  },
  {
    id: "rust-loop",
    language: "rust",
    category: "flow",
    difficulty: "easy",
    label: "for range",
    description: "1〜10 を合計する for ループ",
    code: j("let mut total: u32 = 0;", "for n in 1..=10 {", "  total += n;", "}"),
  },
  {
    id: "rust-fn",
    language: "rust",
    category: "functions",
    difficulty: "medium",
    label: "fn",
    description: "整数を2乗して返す関数",
    code: j("fn square(x: i32) -> i32 {", "  x * x", "}"),
  },
  {
    id: "rust-struct",
    language: "rust",
    category: "basics",
    difficulty: "medium",
    label: "struct",
    description: "名前と年齢を持つ構造体",
    code: j("struct User {", "  name: String,", "  age: u8,", "}"),
  },
  {
    id: "rust-match",
    language: "rust",
    category: "flow",
    difficulty: "medium",
    label: "match",
    description: "Result を match で成功/失敗に分岐する",
    code: j(
      "match result {",
      '  Ok(v) => println!("{v}"),',
      '  Err(e) => eprintln!("{e}"),',
      "}",
    ),
  },
  {
    id: "rust-iter",
    language: "rust",
    category: "functions",
    difficulty: "hard",
    label: "iterator chain",
    description: "イテレータで正の数だけ合計する",
    code: j(
      "let sum: i32 = nums",
      "  .iter()",
      "  .filter(|&&n| n > 0)",
      "  .sum();",
    ),
  },
  {
    id: "rust-option",
    language: "rust",
    category: "flow",
    difficulty: "hard",
    label: "unwrap_or_else",
    description: "None なら既定の文字列を返す",
    code: j('let name = user.name.unwrap_or_else(|| "anon".to_string());'),
  },

  // ---------------- Java ----------------
  {
    id: "java-hello",
    language: "java",
    category: "basics",
    difficulty: "easy",
    label: "println",
    description: "標準出力に文字列を表示する",
    code: j('System.out.println("hello, world");'),
  },
  {
    id: "java-loop",
    language: "java",
    category: "flow",
    difficulty: "easy",
    label: "for loop",
    description: "0〜9 を順に出力する for ループ",
    code: j("for (int i = 0; i < 10; i++) {", "  System.out.println(i);", "}"),
  },
  {
    id: "java-stream",
    language: "java",
    category: "functions",
    difficulty: "medium",
    label: "Stream",
    description: "Stream で偶数だけ集める",
    code: j(
      "List<Integer> evens = nums.stream()",
      "  .filter(n -> n % 2 == 0)",
      "  .toList();",
    ),
  },

  // ---------------- C++ ----------------
  {
    id: "cpp-hello",
    language: "cpp",
    category: "basics",
    difficulty: "easy",
    label: "cout",
    description: "標準出力に文字列を流す",
    code: j('std::cout << "hello, world" << std::endl;'),
  },
  {
    id: "cpp-func",
    language: "cpp",
    category: "functions",
    difficulty: "easy",
    label: "function",
    description: "2つの整数を足して返す関数",
    code: j("int add(int a, int b) {", "  return a + b;", "}"),
  },
  {
    id: "cpp-vector",
    language: "cpp",
    category: "flow",
    difficulty: "medium",
    label: "range for",
    description: "vector を範囲 for で1要素ずつ出力",
    code: j(
      "std::vector<int> nums = {1, 2, 3};",
      "for (int n : nums) {",
      '  std::cout << n << "\\n";',
      "}",
    ),
  },

  // ---------------- SQL ----------------
  {
    id: "sql-select",
    language: "sql",
    category: "basics",
    difficulty: "easy",
    label: "SELECT",
    description: "条件付きで列を取り出す基本のSELECT",
    code: j("SELECT id, name FROM users WHERE active = true;"),
  },
  {
    id: "sql-join",
    language: "sql",
    category: "flow",
    difficulty: "medium",
    label: "JOIN",
    description: "2つのテーブルを結合して取得",
    code: j(
      "SELECT u.name, o.total",
      "FROM users u",
      "JOIN orders o ON o.user_id = u.id;",
    ),
  },
  {
    id: "sql-group",
    language: "sql",
    category: "functions",
    difficulty: "medium",
    label: "GROUP BY",
    description: "カテゴリ別に集計して件数で絞る",
    code: j(
      "SELECT category, COUNT(*) AS n",
      "FROM products",
      "GROUP BY category",
      "HAVING COUNT(*) > 5;",
    ),
  },
];
