import type { Snippet } from "./types.js";

// Join rows into a single `\n`-delimited string. Rows are written as
// single-quoted strings so inner backticks and ${...} stay literal.
const j = (...rows: string[]): string => rows.join("\n");

export const CODE_SNIPPETS: Snippet[] = [
  // ---------------- TypeScript / JavaScript ----------------
  {
    id: "ts-const",
    language: "ts",
    category: "basics",
    difficulty: "easy",
    label: "const & log",
    description: "文字列を定数に入れてコンソール出力する",
    code: j('const greeting = "hello, world";', "console.log(greeting);"),
  },
  {
    id: "ts-ternary",
    language: "ts",
    category: "flow",
    difficulty: "easy",
    label: "Ternary",
    description: "三項演算子で条件によって値を選ぶ",
    code: j('const label = ok ? "yes" : "no";'),
  },
  {
    id: "ts-arrow",
    language: "ts",
    category: "functions",
    difficulty: "easy",
    label: "Arrow fn",
    description: "2つの数値を受け取り和を返すアロー関数",
    code: j("const sum = (a: number, b: number): number => a + b;"),
  },
  {
    id: "ts-chain",
    language: "ts",
    category: "functions",
    difficulty: "medium",
    label: "filter / map",
    description: "偶数だけ絞り込んで2倍にするメソッドチェーン",
    code: j(
      "const doubled = nums",
      "  .filter((n) => n % 2 === 0)",
      "  .map((n) => n * 2);",
    ),
  },
  {
    id: "ts-interface",
    language: "ts",
    category: "basics",
    difficulty: "medium",
    label: "Interface",
    description: "オブジェクトの形を表す interface 定義",
    code: j(
      "interface User {",
      "  id: number;",
      "  name: string;",
      "  active?: boolean;",
      "}",
    ),
  },
  {
    id: "ts-async",
    language: "ts",
    category: "async",
    difficulty: "medium",
    label: "async / await",
    description: "URL を非同期に取得して JSON を返す",
    code: j(
      "async function load(url: string) {",
      "  const res = await fetch(url);",
      "  return res.json();",
      "}",
    ),
  },
  {
    id: "ts-guard",
    language: "ts",
    category: "flow",
    difficulty: "hard",
    label: "Guard clause",
    description: "権限を判定して許可するか例外を投げる",
    code: j(
      'if (user?.role === "admin" && !user.banned) {',
      "  grantAccess();",
      "} else {",
      '  throw new Error("denied");',
      "}",
    ),
  },
  {
    id: "ts-react",
    language: "ts",
    category: "functions",
    difficulty: "hard",
    label: "React hooks",
    description: "state とドキュメントタイトルを同期する hooks",
    code: j(
      "const [count, setCount] = useState(0);",
      "useEffect(() => {",
      "  document.title = `count: ${count}`;",
      "}, [count]);",
    ),
  },

  // ---------------- Python ----------------
  {
    id: "py-print",
    language: "py",
    category: "basics",
    difficulty: "easy",
    label: "print",
    description: "文字列を標準出力する",
    code: j('print("hello, world")'),
  },
  {
    id: "py-fstring",
    language: "py",
    category: "basics",
    difficulty: "easy",
    label: "f-string",
    description: "f-string で変数を埋め込んで出力する",
    code: j('name = "Ada"', 'print(f"hello, {name}!")'),
  },
  {
    id: "py-def",
    language: "py",
    category: "functions",
    difficulty: "easy",
    label: "def",
    description: "2つの引数を足して返す関数定義",
    code: j("def add(a, b):", "    return a + b"),
  },
  {
    id: "py-comp",
    language: "py",
    category: "functions",
    difficulty: "medium",
    label: "Comprehension",
    description: "内包表記で偶数の二乗リストを作る",
    code: j("squares = [x * x for x in range(10) if x % 2 == 0]"),
  },
  {
    id: "py-dict",
    language: "py",
    category: "basics",
    difficulty: "medium",
    label: "Dict literal",
    description: "辞書リテラルで設定値をまとめる",
    code: j("config = {", '    "debug": True,', '    "retries": 3,', "}"),
  },
  {
    id: "py-with",
    language: "py",
    category: "flow",
    difficulty: "medium",
    label: "with / for",
    description: "ファイルを開いて1行ずつ処理する",
    code: j(
      'with open("data.txt") as f:',
      "    for line in f:",
      "        print(line.strip())",
    ),
  },
  {
    id: "py-try",
    language: "py",
    category: "flow",
    difficulty: "hard",
    label: "try / except",
    description: "例外を捕まえて既定値にフォールバックする",
    code: j(
      "try:",
      "    value = int(raw)",
      "except ValueError:",
      "    value = 0",
    ),
  },
  {
    id: "py-decorator",
    language: "py",
    category: "functions",
    difficulty: "hard",
    label: "Decorator",
    description: "デコレータで URL ルーティングを定義する",
    code: j(
      '@app.route("/users/<int:id>")',
      "def get_user(id):",
      "    return jsonify(db.get(id))",
    ),
  },

  // ---------------- Go ----------------
  {
    id: "go-hello",
    language: "go",
    category: "basics",
    difficulty: "easy",
    label: "Println",
    description: "標準出力に文字列を表示する",
    code: j('fmt.Println("hello, world")'),
  },
  {
    id: "go-func",
    language: "go",
    category: "functions",
    difficulty: "easy",
    label: "func",
    description: "2つの整数を足して返す関数",
    code: j("func add(a, b int) int {", "  return a + b", "}"),
  },
  {
    id: "go-struct",
    language: "go",
    category: "basics",
    difficulty: "medium",
    label: "struct",
    description: "座標を表す構造体の定義",
    code: j("type Point struct {", "  X int", "  Y int", "}"),
  },
  {
    id: "go-range",
    language: "go",
    category: "functions",
    difficulty: "medium",
    label: "for range",
    description: "スライスを range で添字付きに反復する",
    code: j(
      "nums := []int{1, 2, 3, 4}",
      "for i, n := range nums {",
      '  fmt.Printf("%d: %d\\n", i, n)',
      "}",
    ),
  },
  {
    id: "go-err",
    language: "go",
    category: "flow",
    difficulty: "hard",
    label: "if err != nil",
    description: "ファイル読込のエラーを早期 return する",
    code: j(
      "data, err := os.ReadFile(path)",
      "if err != nil {",
      "  return nil, err",
      "}",
    ),
  },
  {
    id: "go-goroutine",
    language: "go",
    category: "async",
    difficulty: "hard",
    label: "goroutine",
    description: "goroutine で計算しチャネルで受け取る",
    code: j("go func() {", "  ch <- compute()", "}()", "result := <-ch"),
  },

  // ---------------- Rust ----------------
  {
    id: "rust-hello",
    language: "rust",
    category: "basics",
    difficulty: "easy",
    label: "println!",
    description: "マクロで文字列を表示する",
    code: j('println!("hello, world");'),
  },
  {
    id: "rust-loop",
    language: "rust",
    category: "flow",
    difficulty: "easy",
    label: "for range",
    description: "1〜10 を合計する for ループ",
    code: j("let mut total: u32 = 0;", "for n in 1..=10 {", "  total += n;", "}"),
  },
  {
    id: "rust-fn",
    language: "rust",
    category: "functions",
    difficulty: "medium",
    label: "fn",
    description: "整数を2乗して返す関数",
    code: j("fn square(x: i32) -> i32 {", "  x * x", "}"),
  },
  {
    id: "rust-struct",
    language: "rust",
    category: "basics",
    difficulty: "medium",
    label: "struct",
    description: "名前と年齢を持つ構造体",
    code: j("struct User {", "  name: String,", "  age: u8,", "}"),
  },
  {
    id: "rust-match",
    language: "rust",
    category: "flow",
    difficulty: "medium",
    label: "match",
    description: "Result を match で成功/失敗に分岐する",
    code: j(
      "match result {",
      '  Ok(v) => println!("{v}"),',
      '  Err(e) => eprintln!("{e}"),',
      "}",
    ),
  },
  {
    id: "rust-iter",
    language: "rust",
    category: "functions",
    difficulty: "hard",
    label: "iterator chain",
    description: "イテレータで正の数だけ合計する",
    code: j(
      "let sum: i32 = nums",
      "  .iter()",
      "  .filter(|&&n| n > 0)",
      "  .sum();",
    ),
  },
  {
    id: "rust-option",
    language: "rust",
    category: "flow",
    difficulty: "hard",
    label: "unwrap_or_else",
    description: "None なら既定の文字列を返す",
    code: j('let name = user.name.unwrap_or_else(|| "anon".to_string());'),
  },

  // ---------------- Java ----------------
  {
    id: "java-hello",
    language: "java",
    category: "basics",
    difficulty: "easy",
    label: "println",
    description: "標準出力に文字列を表示する",
    code: j('System.out.println("hello, world");'),
  },
  {
    id: "java-loop",
    language: "java",
    category: "flow",
    difficulty: "easy",
    label: "for loop",
    description: "0〜9 を順に出力する for ループ",
    code: j("for (int i = 0; i < 10; i++) {", "  System.out.println(i);", "}"),
  },
  {
    id: "java-stream",
    language: "java",
    category: "functions",
    difficulty: "medium",
    label: "Stream",
    description: "Stream で偶数だけ集める",
    code: j(
      "List<Integer> evens = nums.stream()",
      "  .filter(n -> n % 2 == 0)",
      "  .toList();",
    ),
  },

  // ---------------- C++ ----------------
  {
    id: "cpp-hello",
    language: "cpp",
    category: "basics",
    difficulty: "easy",
    label: "cout",
    description: "標準出力に文字列を流す",
    code: j('std::cout << "hello, world" << std::endl;'),
  },
  {
    id: "cpp-func",
    language: "cpp",
    category: "functions",
    difficulty: "easy",
    label: "function",
    description: "2つの整数を足して返す関数",
    code: j("int add(int a, int b) {", "  return a + b;", "}"),
  },
  {
    id: "cpp-vector",
    language: "cpp",
    category: "flow",
    difficulty: "medium",
    label: "range for",
    description: "vector を範囲 for で1要素ずつ出力",
    code: j(
      "std::vector<int> nums = {1, 2, 3};",
      "for (int n : nums) {",
      '  std::cout << n << "\\n";',
      "}",
    ),
  },

  // ---------------- SQL ----------------
  {
    id: "sql-select",
    language: "sql",
    category: "basics",
    difficulty: "easy",
    label: "SELECT",
    description: "条件付きで列を取り出す基本のSELECT",
    code: j("SELECT id, name FROM users WHERE active = true;"),
  },
  {
    id: "sql-join",
    language: "sql",
    category: "flow",
    difficulty: "medium",
    label: "JOIN",
    description: "2つのテーブルを結合して取得",
    code: j(
      "SELECT u.name, o.total",
      "FROM users u",
      "JOIN orders o ON o.user_id = u.id;",
    ),
  },
  {
    id: "sql-group",
    language: "sql",
    category: "functions",
    difficulty: "medium",
    label: "GROUP BY",
    description: "カテゴリ別に集計して件数で絞る",
    code: j(
      "SELECT category, COUNT(*) AS n",
      "FROM products",
      "GROUP BY category",
      "HAVING COUNT(*) > 5;",
    ),
  },

  // ---------------- TypeScript / JavaScript (more) ----------------
  {
    id: "ts-destructure",
    language: "ts",
    category: "basics",
    difficulty: "easy",
    label: "Destructuring",
    description: "分割代入で必要な値と残りを取り出す",
    code: j("const { id, name, ...rest } = user;"),
  },
  {
    id: "ts-switch",
    language: "ts",
    category: "flow",
    difficulty: "medium",
    label: "switch",
    description: "switch 文で状態に応じて分岐する",
    code: j(
      "switch (status) {",
      '  case "ok":',
      "    return 200;",
      "  default:",
      "    return 500;",
      "}",
    ),
  },
  {
    id: "ts-promise-all",
    language: "ts",
    category: "async",
    difficulty: "medium",
    label: "Promise.all",
    description: "複数の非同期処理を並行に待つ",
    code: j(
      "const users = await Promise.all(",
      "  ids.map((id) => fetchUser(id)),",
      ");",
    ),
  },
  {
    id: "ts-generic",
    language: "ts",
    category: "functions",
    difficulty: "hard",
    label: "Generics",
    description: "ジェネリクスで型を保ったまま先頭要素を返す",
    code: j(
      "function first<T>(arr: T[]): T | undefined {",
      "  return arr[0];",
      "}",
    ),
  },

  // ---------------- Python (more) ----------------
  {
    id: "py-enumerate",
    language: "py",
    category: "functions",
    difficulty: "easy",
    label: "enumerate",
    description: "enumerate で添字付きに反復する",
    code: j("for i, item in enumerate(items):", "    print(i, item)"),
  },
  {
    id: "py-class",
    language: "py",
    category: "basics",
    difficulty: "medium",
    label: "class",
    description: "コンストラクタを持つクラス定義",
    code: j(
      "class Point:",
      "    def __init__(self, x, y):",
      "        self.x = x",
      "        self.y = y",
    ),
  },
  {
    id: "py-async",
    language: "py",
    category: "async",
    difficulty: "medium",
    label: "async / await",
    description: "非同期にHTTP取得してJSONを返す",
    code: j(
      "async def fetch(url):",
      "    async with session.get(url) as r:",
      "        return await r.json()",
    ),
  },

  // ---------------- Go (more) ----------------
  {
    id: "go-map",
    language: "go",
    category: "basics",
    difficulty: "medium",
    label: "map count",
    description: "map で単語の出現回数を数える",
    code: j(
      "counts := map[string]int{}",
      "for _, w := range words {",
      "  counts[w]++",
      "}",
    ),
  },
  {
    id: "go-defer",
    language: "go",
    category: "flow",
    difficulty: "medium",
    label: "defer close",
    description: "defer でファイルを確実に閉じる",
    code: j(
      "f, err := os.Open(path)",
      "if err != nil {",
      "  return err",
      "}",
      "defer f.Close()",
    ),
  },
  {
    id: "go-interface",
    language: "go",
    category: "basics",
    difficulty: "medium",
    label: "interface",
    description: "メソッドを定義するインターフェース",
    code: j("type Stringer interface {", "  String() string", "}"),
  },

  // ---------------- Rust (more) ----------------
  {
    id: "rust-vec",
    language: "rust",
    category: "basics",
    difficulty: "easy",
    label: "Vec",
    description: "可変ベクタに要素を追加する",
    code: j("let mut v = vec![1, 2, 3];", "v.push(4);"),
  },
  {
    id: "rust-iflet",
    language: "rust",
    category: "flow",
    difficulty: "medium",
    label: "if let",
    description: "if let で Some のときだけ取り出す",
    code: j("if let Some(x) = maybe {", '  println!("{x}");', "}"),
  },
  {
    id: "rust-trait",
    language: "rust",
    category: "basics",
    difficulty: "hard",
    label: "trait",
    description: "面積を返すトレイト定義",
    code: j("trait Shape {", "  fn area(&self) -> f64;", "}"),
  },

  // ---------------- Java (more) ----------------
  {
    id: "java-class",
    language: "java",
    category: "basics",
    difficulty: "medium",
    label: "class",
    description: "フィールドとゲッターを持つクラス",
    code: j(
      "public class User {",
      "  private String name;",
      "  public String getName() {",
      "    return name;",
      "  }",
      "}",
    ),
  },
  {
    id: "java-map",
    language: "java",
    category: "functions",
    difficulty: "medium",
    label: "Map merge",
    description: "Map.merge で出現回数を加算する",
    code: j(
      "Map<String, Integer> counts = new HashMap<>();",
      "counts.merge(word, 1, Integer::sum);",
    ),
  },
  {
    id: "java-try",
    language: "java",
    category: "flow",
    difficulty: "medium",
    label: "try / catch",
    description: "例外を捕捉してログ出力する",
    code: j(
      "try {",
      "  process();",
      "} catch (IOException e) {",
      '  log.error("process failed", e);',
      "}",
    ),
  },

  // ---------------- C++ (more) ----------------
  {
    id: "cpp-class",
    language: "cpp",
    category: "basics",
    difficulty: "medium",
    label: "class",
    description: "公開メンバを持つクラス",
    code: j("class Point {", "public:", "  int x, y;", "};"),
  },
  {
    id: "cpp-auto",
    language: "cpp",
    category: "functions",
    difficulty: "medium",
    label: "auto + range for",
    description: "auto と範囲 for で合計を取る",
    code: j("auto sum = 0;", "for (auto n : nums) sum += n;"),
  },
  {
    id: "cpp-smartptr",
    language: "cpp",
    category: "basics",
    difficulty: "hard",
    label: "unique_ptr",
    description: "スマートポインタを生成して参照する",
    code: j(
      "auto p = std::make_unique<Node>(1);",
      "std::cout << p->value;",
    ),
  },

  // ---------------- SQL (more) ----------------
  {
    id: "sql-insert",
    language: "sql",
    category: "basics",
    difficulty: "easy",
    label: "INSERT",
    description: "テーブルに行を追加する",
    code: j("INSERT INTO users (name, email) VALUES ('Ada', 'ada@x.io');"),
  },
  {
    id: "sql-update",
    language: "sql",
    category: "flow",
    difficulty: "easy",
    label: "UPDATE",
    description: "条件に一致する行を更新する",
    code: j("UPDATE users SET active = false WHERE last_login < '2025-01-01';"),
  },
  {
    id: "sql-subquery",
    language: "sql",
    category: "functions",
    difficulty: "hard",
    label: "Subquery",
    description: "サブクエリで条件に合うユーザーを抽出",
    code: j(
      "SELECT name FROM users",
      "WHERE id IN (SELECT user_id FROM orders WHERE total > 100);",
    ),
  },

  // ---------------- Bash ----------------
  {
    id: "bash-vars",
    language: "bash",
    category: "basics",
    difficulty: "easy",
    label: "variables",
    description: "変数に代入して展開する",
    code: j('name="world"', 'echo "hello, $name"'),
  },
  {
    id: "bash-loop",
    language: "bash",
    category: "flow",
    difficulty: "easy",
    label: "for loop",
    description: "ファイルをループで処理する",
    code: j("for f in *.txt; do", '  echo "$f"', "done"),
  },
  {
    id: "bash-pipe",
    language: "bash",
    category: "functions",
    difficulty: "medium",
    label: "pipe",
    description: "パイプでつないで 404 の行を種類ごとに数える",
    code: j("grep 404 access.log | sort | uniq -c"),
  },
  {
    id: "bash-if",
    language: "bash",
    category: "flow",
    difficulty: "medium",
    label: "if test",
    description: "ファイルの存在を判定する",
    code: j('if [ -f "$1" ]; then', '  echo "exists"', "fi"),
  },
  {
    id: "bash-func",
    language: "bash",
    category: "functions",
    difficulty: "medium",
    label: "function",
    description: "引数を受け取る関数を定義する",
    code: j("greet() {", '  echo "hi, $1"', "}"),
  },

  // ---------------- CSS ----------------
  {
    id: "css-flex",
    language: "css",
    category: "basics",
    difficulty: "easy",
    label: "flexbox",
    description: "フレックスボックスで横並び+間隔",
    code: j(".row {", "  display: flex;", "  gap: 8px;", "}"),
  },
  {
    id: "css-var",
    language: "css",
    category: "basics",
    difficulty: "easy",
    label: "custom property",
    description: "カスタムプロパティ（CSS変数）を定義",
    code: j(":root {", "  --accent: #5cf2ff;", "}"),
  },
  {
    id: "css-grid",
    language: "css",
    category: "basics",
    difficulty: "medium",
    label: "grid",
    description: "グリッドで3カラム等分レイアウト",
    code: j(
      ".grid {",
      "  display: grid;",
      "  grid-template-columns: repeat(3, 1fr);",
      "}",
    ),
  },
  {
    id: "css-media",
    language: "css",
    category: "flow",
    difficulty: "medium",
    label: "media query",
    description: "メディアクエリで縦並びに切替",
    code: j(
      "@media (max-width: 600px) {",
      "  .row { flex-direction: column; }",
      "}",
    ),
  },
  {
    id: "css-transition",
    language: "css",
    category: "functions",
    difficulty: "medium",
    label: "transition",
    description: "ホバー時のトランジションを定義",
    code: j(".btn {", "  transition: transform 0.2s ease;", "}"),
  },

  // ---------------- C# ----------------
  {
    id: "csharp-write",
    language: "csharp",
    category: "basics",
    difficulty: "easy",
    label: "WriteLine",
    description: "コンソールに文字列を出力する",
    code: j('Console.WriteLine("hello, world");'),
  },
  {
    id: "csharp-linq",
    language: "csharp",
    category: "functions",
    difficulty: "medium",
    label: "LINQ",
    description: "LINQ で偶数だけ抽出する",
    code: j("var evens = nums.Where(n => n % 2 == 0).ToList();"),
  },
  {
    id: "csharp-prop",
    language: "csharp",
    category: "basics",
    difficulty: "medium",
    label: "auto-property",
    description: "自動プロパティを持つクラス",
    code: j(
      "public class User {",
      "  public required string Name { get; set; }",
      "}",
    ),
  },
  {
    id: "csharp-foreach",
    language: "csharp",
    category: "flow",
    difficulty: "easy",
    label: "foreach",
    description: "コレクションを foreach で走査する",
    code: j(
      "foreach (var item in items) {",
      "  Console.WriteLine(item);",
      "}",
    ),
  },

  // ---------------- Swift ----------------
  {
    id: "swift-print",
    language: "swift",
    category: "basics",
    difficulty: "easy",
    label: "print",
    description: "標準出力に文字列を表示する",
    code: j('print("hello, world")'),
  },
  {
    id: "swift-map",
    language: "swift",
    category: "functions",
    difficulty: "easy",
    label: "map",
    description: "クロージャ省略記法で2倍にする",
    code: j("let nums = [1, 2, 3]", "let doubled = nums.map { $0 * 2 }"),
  },
  {
    id: "swift-func",
    language: "swift",
    category: "functions",
    difficulty: "medium",
    label: "func",
    description: "2つの整数を足して返す関数",
    code: j("func add(_ a: Int, _ b: Int) -> Int {", "  a + b", "}"),
  },
  {
    id: "swift-guard",
    language: "swift",
    category: "flow",
    difficulty: "medium",
    label: "guard let",
    description: "guard let で早期 return する",
    code: j("guard let name = user.name else {", "  return", "}"),
  },

  // ---------------- Kotlin ----------------
  {
    id: "kotlin-fun",
    language: "kotlin",
    category: "functions",
    difficulty: "easy",
    label: "fun (expression)",
    description: "式本体の関数定義",
    code: j("fun add(a: Int, b: Int) = a + b"),
  },
  {
    id: "kotlin-val",
    language: "kotlin",
    category: "basics",
    difficulty: "easy",
    label: "val + sum",
    description: "リストを作って合計する",
    code: j("val nums = listOf(1, 2, 3)", "val sum = nums.sum()"),
  },
  {
    id: "kotlin-data",
    language: "kotlin",
    category: "basics",
    difficulty: "medium",
    label: "data class",
    description: "データクラスを1行で定義",
    code: j("data class User(val id: Int, val name: String)"),
  },
  {
    id: "kotlin-when",
    language: "kotlin",
    category: "flow",
    difficulty: "medium",
    label: "when",
    description: "when 式で値によって分岐する",
    code: j("when (status) {", '  200 -> "ok"', '  else -> "error"', "}"),
  },

  // ---------------- Ruby ----------------
  {
    id: "ruby-puts",
    language: "ruby",
    category: "basics",
    difficulty: "easy",
    label: "puts",
    description: "標準出力に文字列を表示する",
    code: j('puts "hello, world"'),
  },
  {
    id: "ruby-each",
    language: "ruby",
    category: "functions",
    difficulty: "easy",
    label: "each block",
    description: "ブロックで配列を反復する",
    code: j("[1, 2, 3].each { |n| puts n }"),
  },
  {
    id: "ruby-method",
    language: "ruby",
    category: "functions",
    difficulty: "medium",
    label: "method",
    description: "文字列補間で挨拶を返すメソッド",
    code: j("def greet(name)", '  "hi, #{name}"', "end"),
  },
  {
    id: "ruby-map",
    language: "ruby",
    category: "functions",
    difficulty: "medium",
    label: "map + select",
    description: "select と map をチェーンする",
    code: j("evens = nums.select { |n| n.even? }.map { |n| n * 2 }"),
  },

  // ---------------- PHP ----------------
  {
    id: "php-echo",
    language: "php",
    category: "basics",
    difficulty: "easy",
    label: "echo",
    description: "文字列を出力する",
    code: j('echo "hello, world";'),
  },
  {
    id: "php-array",
    language: "php",
    category: "functions",
    difficulty: "medium",
    label: "array_filter",
    description: "アロー関数で正の数だけ残す",
    code: j("$nums = array_filter($xs, fn($n) => $n > 0);"),
  },
  {
    id: "php-foreach",
    language: "php",
    category: "flow",
    difficulty: "medium",
    label: "foreach",
    description: "オブジェクト配列を foreach で走査",
    code: j("foreach ($users as $user) {", "  echo $user->name;", "}"),
  },

  // ---------------- HTML ----------------
  {
    id: "html-link",
    language: "html",
    category: "basics",
    difficulty: "easy",
    label: "anchor",
    description: "リンク（アンカー）要素",
    code: j('<a href="/about">About</a>'),
  },
  {
    id: "html-img",
    language: "html",
    category: "basics",
    difficulty: "easy",
    label: "img",
    description: "alt 付きの画像要素",
    code: j('<img src="logo.png" alt="logo" />'),
  },
  {
    id: "html-list",
    language: "html",
    category: "basics",
    difficulty: "medium",
    label: "list",
    description: "箇条書きリスト",
    code: j("<ul>", "  <li>one</li>", "  <li>two</li>", "</ul>"),
  },
  {
    id: "html-input",
    language: "html",
    category: "functions",
    difficulty: "medium",
    label: "labeled input",
    description: "ラベル付きの入力フォーム",
    code: j(
      "<label>",
      "  Email",
      '  <input type="email" name="email" />',
      "</label>",
    ),
  },

  // ---------------- TypeScript / JavaScript (idioms) ----------------
  {
    id: "ts-nullish",
    language: "ts",
    category: "basics",
    difficulty: "easy",
    label: "?. and ??",
    description: "オプショナルチェーンと ?? で既定値にフォールバックする",
    code: j('const city = user?.address?.city ?? "unknown";'),
  },
  {
    id: "ts-union",
    language: "ts",
    category: "basics",
    difficulty: "medium",
    label: "Union type",
    description: "判別可能なユニオン型で図形を表す",
    code: j(
      "type Shape =",
      '  | { kind: "circle"; r: number }',
      '  | { kind: "rect"; w: number; h: number };',
    ),
  },
  {
    id: "ts-class",
    language: "ts",
    category: "basics",
    difficulty: "medium",
    label: "class (#private)",
    description: "プライベートフィールドを持つクラス",
    code: j(
      "class Counter {",
      "  #count = 0;",
      "  increment(): number {",
      "    return ++this.#count;",
      "  }",
      "}",
    ),
  },
  {
    id: "ts-for-of",
    language: "ts",
    category: "flow",
    difficulty: "easy",
    label: "for...of entries",
    description: "オブジェクトのキーと値を for...of で走査する",
    code: j(
      "for (const [key, value] of Object.entries(scores)) {",
      "  console.log(key, value);",
      "}",
    ),
  },
  {
    id: "ts-try-catch",
    language: "ts",
    category: "flow",
    difficulty: "medium",
    label: "try / catch",
    description: "JSON のパース失敗を捕まえてログに出す",
    code: j(
      "try {",
      "  const data = JSON.parse(text);",
      "  render(data);",
      "} catch (err) {",
      "  console.error(err);",
      "}",
    ),
  },
  {
    id: "ts-reduce",
    language: "ts",
    category: "functions",
    difficulty: "medium",
    label: "reduce",
    description: "reduce で合計金額を畳み込む",
    code: j(
      "const total = items.reduce(",
      "  (sum, item) => sum + item.price * item.qty,",
      "  0,",
      ");",
    ),
  },
  {
    id: "ts-keyof",
    language: "ts",
    category: "functions",
    difficulty: "hard",
    label: "keyof",
    description: "keyof で型安全にプロパティを取り出す",
    code: j(
      "function pick<T, K extends keyof T>(obj: T, key: K): T[K] {",
      "  return obj[key];",
      "}",
    ),
  },
  {
    id: "ts-debounce",
    language: "ts",
    category: "functions",
    difficulty: "hard",
    label: "Debounce",
    description: "連続した呼び出しを最後の1回にまとめるデバウンス",
    code: j(
      "function debounce(fn: () => void, ms: number) {",
      "  let timer: ReturnType<typeof setTimeout>;",
      "  return () => {",
      "    clearTimeout(timer);",
      "    timer = setTimeout(fn, ms);",
      "  };",
      "}",
    ),
  },
  {
    id: "ts-fetch-timeout",
    language: "ts",
    category: "async",
    difficulty: "hard",
    label: "fetch + timeout",
    description: "タイムアウト付きで取得し失敗ステータスを例外にする",
    code: j(
      "const res = await fetch(url, {",
      "  signal: AbortSignal.timeout(5000),",
      "});",
      "if (!res.ok) throw new Error(`HTTP ${res.status}`);",
    ),
  },

  // ---------------- Python (idioms) ----------------
  {
    id: "py-unpack",
    language: "py",
    category: "basics",
    difficulty: "easy",
    label: "Unpack & slice",
    description: "アンパックとスライスでリストを分ける",
    code: j("first, *rest = items", "last_three = items[-3:]"),
  },
  {
    id: "py-dataclass",
    language: "py",
    category: "basics",
    difficulty: "medium",
    label: "dataclass",
    description: "dataclass で型付きのデータクラスを定義する",
    code: j("@dataclass", "class User:", "    name: str", "    age: int = 0"),
  },
  {
    id: "py-sort-key",
    language: "py",
    category: "functions",
    difficulty: "easy",
    label: "sort key",
    description: "lambda をキーにして降順ソートする",
    code: j('users.sort(key=lambda u: u["age"], reverse=True)'),
  },
  {
    id: "py-dict-comp",
    language: "py",
    category: "functions",
    difficulty: "medium",
    label: "Dict comprehension",
    description: "辞書内包表記で単語と長さの対応を作る",
    code: j("lengths = {word: len(word) for word in words}"),
  },
  {
    id: "py-generator",
    language: "py",
    category: "functions",
    difficulty: "hard",
    label: "Generator",
    description: "yield でリストを一定サイズずつ区切って返す",
    code: j(
      "def chunks(items, size):",
      "    for i in range(0, len(items), size):",
      "        yield items[i : i + size]",
    ),
  },
  {
    id: "py-zip",
    language: "py",
    category: "flow",
    difficulty: "easy",
    label: "zip",
    description: "zip で2つのリストを同時に反復する",
    code: j("for name, score in zip(names, scores):", '    print(f"{name}: {score}")'),
  },
  {
    id: "py-walrus",
    language: "py",
    category: "flow",
    difficulty: "medium",
    label: "Walrus :=",
    description: "代入式で検索結果を受けてそのまま判定する",
    code: j('if m := re.search(r"\\d+", text):', "    print(m.group())"),
  },
  {
    id: "py-match",
    language: "py",
    category: "flow",
    difficulty: "hard",
    label: "match / case",
    description: "構造的パターンマッチでコマンドを分岐する",
    code: j(
      "match command.split():",
      '    case ["go", direction]:',
      "        move(direction)",
      '    case ["quit"]:',
      "        stop()",
      "    case _:",
      '        print("unknown command")',
    ),
  },
  {
    id: "py-gather",
    language: "py",
    category: "async",
    difficulty: "hard",
    label: "asyncio.gather",
    description: "複数のコルーチンを並行に実行して待つ",
    code: j(
      "async def main():",
      "    pages = await asyncio.gather(*map(fetch, urls))",
      "    print(len(pages))",
    ),
  },

  // ---------------- Go (idioms) ----------------
  {
    id: "go-append",
    language: "go",
    category: "basics",
    difficulty: "easy",
    label: "append",
    description: "スライスに要素を追加する",
    code: j("nums := []int{1, 2, 3}", "nums = append(nums, 4, 5)"),
  },
  {
    id: "go-json-tags",
    language: "go",
    category: "basics",
    difficulty: "hard",
    label: "struct tags",
    description: "JSON タグ付きの構造体定義",
    code: j(
      "type User struct {",
      '  Name string `json:"name"`',
      '  Mail string `json:"mail,omitempty"`',
      "}",
    ),
  },
  {
    id: "go-method",
    language: "go",
    category: "functions",
    difficulty: "medium",
    label: "method",
    description: "構造体にメソッドを定義する",
    code: j("func (c Circle) Area() float64 {", "  return math.Pi * c.R * c.R", "}"),
  },
  {
    id: "go-errors-new",
    language: "go",
    category: "functions",
    difficulty: "medium",
    label: "(value, error)",
    description: "値とエラーの2つを返す関数",
    code: j(
      "func divide(a, b float64) (float64, error) {",
      "  if b == 0 {",
      '    return 0, errors.New("division by zero")',
      "  }",
      "  return a / b, nil",
      "}",
    ),
  },
  {
    id: "go-generics",
    language: "go",
    category: "functions",
    difficulty: "hard",
    label: "generics",
    description: "型パラメータで汎用の Map 関数を書く",
    code: j(
      "func Map[T, U any](xs []T, f func(T) U) []U {",
      "  out := make([]U, 0, len(xs))",
      "  for _, x := range xs {",
      "    out = append(out, f(x))",
      "  }",
      "  return out",
      "}",
    ),
  },
  {
    id: "go-switch",
    language: "go",
    category: "flow",
    difficulty: "easy",
    label: "switch",
    description: "複数の値をまとめて分岐する switch",
    code: j(
      "switch day {",
      'case "sat", "sun":',
      '  fmt.Println("weekend")',
      "default:",
      '  fmt.Println("weekday")',
      "}",
    ),
  },
  {
    id: "go-errorf",
    language: "go",
    category: "flow",
    difficulty: "medium",
    label: "wrap error (%w)",
    description: "エラーを %w で包んで文脈を足す",
    code: j("if err := run(); err != nil {", '  return fmt.Errorf("run: %w", err)', "}"),
  },
  {
    id: "go-waitgroup",
    language: "go",
    category: "async",
    difficulty: "hard",
    label: "WaitGroup",
    description: "WaitGroup で全ゴルーチンの完了を待つ",
    code: j(
      "var wg sync.WaitGroup",
      "for _, url := range urls {",
      "  wg.Go(func() {",
      "    fetch(url)",
      "  })",
      "}",
      "wg.Wait()",
    ),
  },
  {
    id: "go-select",
    language: "go",
    category: "async",
    difficulty: "hard",
    label: "select timeout",
    description: "select でタイムアウト付きの受信をする",
    code: j(
      "select {",
      "case msg := <-ch:",
      "  fmt.Println(msg)",
      "case <-time.After(time.Second):",
      '  fmt.Println("timeout")',
      "}",
    ),
  },

  // ---------------- Rust (idioms) ----------------
  {
    id: "rust-string",
    language: "rust",
    category: "basics",
    difficulty: "easy",
    label: "String",
    description: "可変の String に文字列を追記する",
    code: j('let mut s = String::from("hello");', 's.push_str(", world");'),
  },
  {
    id: "rust-enum",
    language: "rust",
    category: "basics",
    difficulty: "medium",
    label: "enum",
    description: "データを持つ列挙型を定義する",
    code: j("enum Shape {", "  Circle(f64),", "  Rect { w: f64, h: f64 },", "}"),
  },
  {
    id: "rust-hashmap",
    language: "rust",
    category: "basics",
    difficulty: "hard",
    label: "HashMap entry",
    description: "entry API で単語の出現回数を数える",
    code: j(
      "let mut counts: HashMap<&str, u32> = HashMap::new();",
      "for word in text.split_whitespace() {",
      "  *counts.entry(word).or_insert(0) += 1;",
      "}",
    ),
  },
  {
    id: "rust-impl",
    language: "rust",
    category: "functions",
    difficulty: "medium",
    label: "impl",
    description: "impl で関連関数（コンストラクタ）を定義する",
    code: j(
      "impl User {",
      "  fn new(name: &str) -> Self {",
      "    Self { name: name.to_string(), age: 0 }",
      "  }",
      "}",
    ),
  },
  {
    id: "rust-collect",
    language: "rust",
    category: "functions",
    difficulty: "medium",
    label: "map + collect",
    description: "map した結果を Vec に集める",
    code: j(
      "let names: Vec<String> = users",
      "  .iter()",
      "  .map(|u| u.name.to_uppercase())",
      "  .collect();",
    ),
  },
  {
    id: "rust-lifetime",
    language: "rust",
    category: "functions",
    difficulty: "hard",
    label: "lifetime",
    description: "ライフタイム注釈を付けて長い方の参照を返す",
    code: j(
      "fn longest<'a>(a: &'a str, b: &'a str) -> &'a str {",
      "  if a.len() >= b.len() { a } else { b }",
      "}",
    ),
  },
  {
    id: "rust-match-guard",
    language: "rust",
    category: "flow",
    difficulty: "medium",
    label: "match guard",
    description: "ガード付きの match で符号を判定する",
    code: j(
      "let sign = match n {",
      '  0 => "zero",',
      '  x if x < 0 => "negative",',
      '  _ => "positive",',
      "};",
    ),
  },
  {
    id: "rust-question",
    language: "rust",
    category: "flow",
    difficulty: "hard",
    label: "? operator",
    description: "? 演算子でエラーを呼び出し元へ伝播する",
    code: j(
      "fn read_port(path: &str) -> Result<u16, Box<dyn Error>> {",
      "  let text = fs::read_to_string(path)?;",
      "  Ok(text.trim().parse()?)",
      "}",
    ),
  },
  {
    id: "rust-thread",
    language: "rust",
    category: "async",
    difficulty: "hard",
    label: "thread::spawn",
    description: "スレッドで合計を計算して join で受け取る",
    code: j(
      "let handle = thread::spawn(move || {",
      "  nums.iter().sum::<i32>()",
      "});",
      "let total = handle.join().unwrap();",
    ),
  },
  {
    id: "rust-async",
    language: "rust",
    category: "async",
    difficulty: "hard",
    label: "async / await",
    description: "非同期に HTTP 取得して本文の長さを返す",
    code: j(
      "async fn fetch_len(url: &str) -> Result<usize, Error> {",
      "  let body = reqwest::get(url).await?.text().await?;",
      "  Ok(body.len())",
      "}",
    ),
  },

  // ---------------- Java (idioms) ----------------
  {
    id: "java-var",
    language: "java",
    category: "basics",
    difficulty: "easy",
    label: "var + List.of",
    description: "var と List.of で不変リストを作る",
    code: j(
      'var names = List.of("Ada", "Linus", "Grace");',
      "System.out.println(names.size());",
    ),
  },
  {
    id: "java-main",
    language: "java",
    category: "basics",
    difficulty: "medium",
    label: "main method",
    description: "エントリポイントの main メソッド",
    code: j(
      "public class Main {",
      "  public static void main(String[] args) {",
      "    System.out.println(args.length);",
      "  }",
      "}",
    ),
  },
  {
    id: "java-record",
    language: "java",
    category: "basics",
    difficulty: "medium",
    label: "record",
    description: "record で不変のデータ型を定義する",
    code: j(
      "public record Point(int x, int y) {",
      "  double norm() {",
      "    return Math.hypot(x, y);",
      "  }",
      "}",
    ),
  },
  {
    id: "java-foreach",
    language: "java",
    category: "flow",
    difficulty: "easy",
    label: "for-each",
    description: "拡張 for でコレクションを走査する",
    code: j("for (String name : names) {", "  System.out.println(name);", "}"),
  },
  {
    id: "java-switch-expr",
    language: "java",
    category: "flow",
    difficulty: "medium",
    label: "switch expression",
    description: "switch 式で曜日からラベルを決める",
    code: j(
      "String label = switch (day) {",
      '  case SAT, SUN -> "weekend";',
      '  default -> "weekday";',
      "};",
    ),
  },
  {
    id: "java-try-resources",
    language: "java",
    category: "flow",
    difficulty: "hard",
    label: "try-with-resources",
    description: "try-with-resources で確実に閉じて1行読む",
    code: j(
      "try (var reader = Files.newBufferedReader(path)) {",
      "  return reader.readLine();",
      "}",
    ),
  },
  {
    id: "java-optional",
    language: "java",
    category: "functions",
    difficulty: "medium",
    label: "Optional",
    description: "Optional で null を安全に既定値へ変換する",
    code: j(
      "String name = Optional.ofNullable(user)",
      "  .map(User::getName)",
      '  .orElse("anonymous");',
    ),
  },
  {
    id: "java-generic",
    language: "java",
    category: "functions",
    difficulty: "hard",
    label: "generic method",
    description: "境界付きジェネリクスで大きい方を返す",
    code: j(
      "static <T extends Comparable<T>> T max(T a, T b) {",
      "  return a.compareTo(b) >= 0 ? a : b;",
      "}",
    ),
  },
  {
    id: "java-future",
    language: "java",
    category: "async",
    difficulty: "hard",
    label: "CompletableFuture",
    description: "CompletableFuture で非同期処理をつなぐ",
    code: j(
      "CompletableFuture",
      "  .supplyAsync(() -> fetch(url))",
      "  .thenApply(String::length)",
      "  .thenAccept(System.out::println);",
    ),
  },

  // ---------------- C++ (idioms) ----------------
  {
    id: "cpp-string",
    language: "cpp",
    category: "basics",
    difficulty: "easy",
    label: "std::string",
    description: "文字列を連結して出力する",
    code: j('std::string name = "world";', 'std::cout << "hello, " + name << "\\n";'),
  },
  {
    id: "cpp-enum-class",
    language: "cpp",
    category: "basics",
    difficulty: "medium",
    label: "enum class",
    description: "スコープ付き列挙型を定義して使う",
    code: j("enum class Color { Red, Green, Blue };", "Color c = Color::Green;"),
  },
  {
    id: "cpp-ctor",
    language: "cpp",
    category: "basics",
    difficulty: "hard",
    label: "constructor",
    description: "初期化子リストと const メンバ関数を持つクラス",
    code: j(
      "class Account {",
      "public:",
      "  explicit Account(double b) : balance_(b) {}",
      "  double balance() const { return balance_; }",
      "private:",
      "  double balance_;",
      "};",
    ),
  },
  {
    id: "cpp-lambda",
    language: "cpp",
    category: "functions",
    difficulty: "medium",
    label: "lambda + sort",
    description: "ラムダを比較関数にして降順ソートする",
    code: j("std::sort(v.begin(), v.end(), [](int a, int b) {", "  return a > b;", "});"),
  },
  {
    id: "cpp-template",
    language: "cpp",
    category: "functions",
    difficulty: "hard",
    label: "template",
    description: "テンプレートで型に依らない clamp を書く",
    code: j(
      "template <typename T>",
      "T clamp(T value, T lo, T hi) {",
      "  return std::max(lo, std::min(value, hi));",
      "}",
    ),
  },
  {
    id: "cpp-ranges",
    language: "cpp",
    category: "functions",
    difficulty: "hard",
    label: "ranges pipeline",
    description: "ranges のパイプで偶数だけ二乗する",
    code: j(
      "auto squares = nums",
      "  | std::views::filter([](int n) { return n % 2 == 0; })",
      "  | std::views::transform([](int n) { return n * n; });",
    ),
  },
  {
    id: "cpp-bindings",
    language: "cpp",
    category: "flow",
    difficulty: "medium",
    label: "structured bindings",
    description: "構造化束縛で map のキーと値を走査する",
    code: j(
      "for (const auto& [name, score] : scores) {",
      '  std::cout << name << ": " << score << "\\n";',
      "}",
    ),
  },
  {
    id: "cpp-if-init",
    language: "cpp",
    category: "flow",
    difficulty: "hard",
    label: "if with initializer",
    description: "初期化付き if で map を検索して返す",
    code: j(
      "if (auto it = cache.find(key); it != cache.end()) {",
      "  return it->second;",
      "}",
    ),
  },
  {
    id: "cpp-async",
    language: "cpp",
    category: "async",
    difficulty: "hard",
    label: "std::async",
    description: "std::async で別スレッドの結果を受け取る",
    code: j(
      "auto task = std::async(std::launch::async, compute);",
      'std::cout << task.get() << "\\n";',
    ),
  },

  // ---------------- C# (idioms) ----------------
  {
    id: "csharp-interp",
    language: "csharp",
    category: "basics",
    difficulty: "easy",
    label: "string interpolation",
    description: "文字列補間で変数を埋め込む",
    code: j('var name = "Ada";', 'Console.WriteLine($"hello, {name}!");'),
  },
  {
    id: "csharp-record",
    language: "csharp",
    category: "basics",
    difficulty: "easy",
    label: "record",
    description: "record で不変のデータ型を1行で定義する",
    code: j("public record User(int Id, string Name);"),
  },
  {
    id: "csharp-dict",
    language: "csharp",
    category: "basics",
    difficulty: "medium",
    label: "Dictionary",
    description: "インデクサ初期化子で辞書を作る",
    code: j(
      "var ages = new Dictionary<string, int> {",
      '  ["Ada"] = 36,',
      '  ["Linus"] = 28,',
      "};",
    ),
  },
  {
    id: "csharp-expr-body",
    language: "csharp",
    category: "functions",
    difficulty: "easy",
    label: "expression body",
    description: "式形式のメンバーで関数を1行で書く",
    code: j("static int Square(int x) => x * x;"),
  },
  {
    id: "csharp-linq-chain",
    language: "csharp",
    category: "functions",
    difficulty: "hard",
    label: "LINQ chain",
    description: "LINQ で絞り込み・並べ替え・射影をつなぐ",
    code: j(
      "var top = users",
      "  .Where(u => u.Active)",
      "  .OrderByDescending(u => u.Score)",
      "  .Select(u => u.Name)",
      "  .Take(3);",
    ),
  },
  {
    id: "csharp-null",
    language: "csharp",
    category: "flow",
    difficulty: "medium",
    label: "?. and ??",
    description: "null 条件演算子と ?? で既定値にする",
    code: j('var city = user?.Address?.City ?? "unknown";'),
  },
  {
    id: "csharp-switch-expr",
    language: "csharp",
    category: "flow",
    difficulty: "hard",
    label: "switch expression",
    description: "関係パターンの switch 式で成績を決める",
    code: j(
      "var grade = score switch {",
      '  >= 90 => "A",',
      '  >= 70 => "B",',
      '  _ => "C",',
      "};",
    ),
  },
  {
    id: "csharp-async",
    language: "csharp",
    category: "async",
    difficulty: "medium",
    label: "async / await",
    description: "HttpClient で非同期に取得して本文を返す",
    code: j(
      "public async Task<string> LoadAsync(string url) {",
      "  var res = await client.GetAsync(url);",
      "  res.EnsureSuccessStatusCode();",
      "  return await res.Content.ReadAsStringAsync();",
      "}",
    ),
  },
  {
    id: "csharp-whenall",
    language: "csharp",
    category: "async",
    difficulty: "hard",
    label: "Task.WhenAll",
    description: "複数のタスクを並行に実行して待つ",
    code: j("var pages = await Task.WhenAll(urls.Select(LoadAsync));"),
  },

  // ---------------- Swift (idioms) ----------------
  {
    id: "swift-interp",
    language: "swift",
    category: "basics",
    difficulty: "easy",
    label: "string interpolation",
    description: "文字列補間で変数を埋め込む",
    code: j('let name = "Ada"', 'print("hello, \\(name)!")'),
  },
  {
    id: "swift-struct",
    language: "swift",
    category: "basics",
    difficulty: "medium",
    label: "struct",
    description: "プロパティを持つ構造体を定義する",
    code: j("struct Point {", "  var x: Double", "  var y: Double", "}"),
  },
  {
    id: "swift-view",
    language: "swift",
    category: "basics",
    difficulty: "hard",
    label: "SwiftUI View",
    description: "状態を持つ SwiftUI のビュー",
    code: j(
      "struct CounterView: View {",
      "  @State private var count = 0",
      "  var body: some View {",
      '    Button("Count: \\(count)") { count += 1 }',
      "  }",
      "}",
    ),
  },
  {
    id: "swift-reduce",
    language: "swift",
    category: "functions",
    difficulty: "medium",
    label: "filter + reduce",
    description: "正の値だけ絞り込んで合計する",
    code: j("let total = prices.filter { $0 > 0 }.reduce(0, +)"),
  },
  {
    id: "swift-extension",
    language: "swift",
    category: "functions",
    difficulty: "hard",
    label: "extension where",
    description: "条件付き extension で配列に合計を生やす",
    code: j(
      "extension Array where Element: Numeric {",
      "  var total: Element { reduce(0, +) }",
      "}",
    ),
  },
  {
    id: "swift-if-let",
    language: "swift",
    category: "flow",
    difficulty: "easy",
    label: "if let",
    description: "if let でオプショナルを安全に取り出す",
    code: j("if let first = names.first {", "  print(first)", "}"),
  },
  {
    id: "swift-switch",
    language: "swift",
    category: "flow",
    difficulty: "medium",
    label: "switch enum",
    description: "列挙型を switch で網羅的に分岐する",
    code: j(
      "switch direction {",
      "case .north, .south:",
      '  print("vertical")',
      "case .east, .west:",
      '  print("horizontal")',
      "}",
    ),
  },
  {
    id: "swift-do-catch",
    language: "swift",
    category: "flow",
    difficulty: "hard",
    label: "do / catch",
    description: "throws する処理を do-catch で受ける",
    code: j(
      "do {",
      "  let text = try String(contentsOf: url, encoding: .utf8)",
      "  print(text.count)",
      "} catch {",
      '  print("failed: \\(error)")',
      "}",
    ),
  },
  {
    id: "swift-async",
    language: "swift",
    category: "async",
    difficulty: "hard",
    label: "async / await",
    description: "async/await でデータを非同期に取得する",
    code: j(
      "func load(_ url: URL) async throws -> Data {",
      "  let (data, _) = try await session.data(from: url)",
      "  return data",
      "}",
    ),
  },

  // ---------------- Kotlin (idioms) ----------------
  {
    id: "kotlin-template",
    language: "kotlin",
    category: "basics",
    difficulty: "easy",
    label: "string template",
    description: "文字列テンプレートで変数を埋め込む",
    code: j('val name = "Ada"', 'println("hello, $name!")'),
  },
  {
    id: "kotlin-class",
    language: "kotlin",
    category: "basics",
    difficulty: "medium",
    label: "class",
    description: "プライマリコンストラクタを持つクラス",
    code: j(
      "class Counter(private var count: Int = 0) {",
      "  fun increment() = ++count",
      "}",
    ),
  },
  {
    id: "kotlin-sealed",
    language: "kotlin",
    category: "basics",
    difficulty: "hard",
    label: "sealed interface",
    description: "sealed interface で画面の状態を表す",
    code: j(
      "sealed interface UiState",
      "data object Loading : UiState",
      "data class Loaded(val items: List<String>) : UiState",
      "data class Failed(val error: Throwable) : UiState",
    ),
  },
  {
    id: "kotlin-lambda",
    language: "kotlin",
    category: "functions",
    difficulty: "medium",
    label: "filter + map",
    description: "ラムダで絞り込みと変換をつなぐ",
    code: j("val names = users", "  .filter { it.age >= 18 }", "  .map { it.name }"),
  },
  {
    id: "kotlin-extension",
    language: "kotlin",
    category: "functions",
    difficulty: "medium",
    label: "extension fun",
    description: "拡張関数で String にメソッドを足す",
    code: j('fun String.shout() = uppercase() + "!"'),
  },
  {
    id: "kotlin-elvis",
    language: "kotlin",
    category: "flow",
    difficulty: "easy",
    label: "?. and ?:",
    description: "セーフコールとエルビス演算子で既定値にする",
    code: j("val length = name?.length ?: 0"),
  },
  {
    id: "kotlin-for",
    language: "kotlin",
    category: "flow",
    difficulty: "easy",
    label: "for range",
    description: "範囲と step で1つ飛ばしに反復する",
    code: j("for (i in 1..9 step 2) {", "  println(i)", "}"),
  },
  {
    id: "kotlin-when-is",
    language: "kotlin",
    category: "flow",
    difficulty: "hard",
    label: "when + smart cast",
    description: "when の型判定とスマートキャストで分岐する",
    code: j(
      "fun describe(x: Any) = when (x) {",
      '  is Int -> "int ${x + 1}"',
      '  is String -> "string of ${x.length}"',
      '  else -> "unknown"',
      "}",
    ),
  },
  {
    id: "kotlin-coroutine",
    language: "kotlin",
    category: "async",
    difficulty: "hard",
    label: "coroutines",
    description: "コルーチンで並行に取得して全件待つ",
    code: j(
      "suspend fun loadAll(ids: List<Int>) = coroutineScope {",
      "  ids.map { async { fetchUser(it) } }.awaitAll()",
      "}",
    ),
  },

  // ---------------- Ruby (idioms) ----------------
  {
    id: "ruby-hash",
    language: "ruby",
    category: "basics",
    difficulty: "easy",
    label: "hash",
    description: "シンボルをキーにしたハッシュ",
    code: j('user = { name: "Ada", age: 36 }', "puts user[:name]"),
  },
  {
    id: "ruby-class",
    language: "ruby",
    category: "basics",
    difficulty: "medium",
    label: "class",
    description: "attr_reader と initialize を持つクラス",
    code: j(
      "class User",
      "  attr_reader :name",
      "  def initialize(name)",
      "    @name = name",
      "  end",
      "end",
    ),
  },
  {
    id: "ruby-to-proc",
    language: "ruby",
    category: "functions",
    difficulty: "easy",
    label: "&:symbol",
    description: "&:name で map して並べ替え・重複除去する",
    code: j("names = users.map(&:name).sort.uniq"),
  },
  {
    id: "ruby-kwargs",
    language: "ruby",
    category: "functions",
    difficulty: "medium",
    label: "keyword args",
    description: "既定値付きのキーワード引数",
    code: j('def greet(name:, greeting: "hello")', '  "#{greeting}, #{name}!"', "end"),
  },
  {
    id: "ruby-retry",
    language: "ruby",
    category: "functions",
    difficulty: "hard",
    label: "yield + retry",
    description: "ブロックを受け取り失敗時に再試行する",
    code: j(
      "def with_retry(times)",
      "  yield",
      "rescue StandardError",
      "  retry if (times -= 1) > 0",
      "  raise",
      "end",
    ),
  },
  {
    id: "ruby-if-modifier",
    language: "ruby",
    category: "flow",
    difficulty: "easy",
    label: "if modifier",
    description: "後置 if で条件付きに出力する",
    code: j('puts "cart is empty" if items.empty?'),
  },
  {
    id: "ruby-case",
    language: "ruby",
    category: "flow",
    difficulty: "medium",
    label: "case / when",
    description: "範囲を使った case 式で成績を出す",
    code: j(
      "case score",
      'when 90..100 then puts "A"',
      'when 70...90 then puts "B"',
      'else puts "C"',
      "end",
    ),
  },
  {
    id: "ruby-rescue",
    language: "ruby",
    category: "flow",
    difficulty: "hard",
    label: "begin / rescue",
    description: "例外を rescue し ensure で後始末する",
    code: j(
      "begin",
      "  data = JSON.parse(text)",
      "rescue JSON::ParserError => e",
      '  warn "bad json: #{e.message}"',
      "ensure",
      "  file.close",
      "end",
    ),
  },
  {
    id: "ruby-thread",
    language: "ruby",
    category: "async",
    difficulty: "hard",
    label: "Thread",
    description: "スレッドで並行に取得して結果を集める",
    code: j(
      "threads = urls.map do |url|",
      "  Thread.new { fetch(url) }",
      "end",
      "pages = threads.map(&:value)",
    ),
  },

  // ---------------- PHP (idioms) ----------------
  {
    id: "php-interp",
    language: "php",
    category: "basics",
    difficulty: "easy",
    label: "interpolation",
    description: "文字列に変数を埋め込んで出力する",
    code: j('$name = "Ada";', 'echo "hello, {$name}!";'),
  },
  {
    id: "php-assoc",
    language: "php",
    category: "basics",
    difficulty: "medium",
    label: "assoc array",
    description: "連想配列でユーザー情報をまとめる",
    code: j("$user = [", '  "name" => "Ada",', '  "age" => 36,', "];"),
  },
  {
    id: "php-class",
    language: "php",
    category: "basics",
    difficulty: "hard",
    label: "constructor promotion",
    description: "コンストラクタ昇格でプロパティを宣言する",
    code: j(
      "class User {",
      "  public function __construct(",
      "    private string $name,",
      "    private int $age = 0,",
      "  ) {}",
      "}",
    ),
  },
  {
    id: "php-function",
    language: "php",
    category: "functions",
    difficulty: "easy",
    label: "typed function",
    description: "型宣言付きの関数定義",
    code: j("function add(int $a, int $b): int {", "  return $a + $b;", "}"),
  },
  {
    id: "php-usort",
    language: "php",
    category: "functions",
    difficulty: "hard",
    label: "usort + <=>",
    description: "宇宙船演算子で年齢順に並べ替える",
    code: j("usort($users, fn($a, $b) => $a->age <=> $b->age);"),
  },
  {
    id: "php-pdo",
    language: "php",
    category: "functions",
    difficulty: "hard",
    label: "PDO prepare",
    description: "プリペアドステートメントで1行取得する",
    code: j(
      '$stmt = $pdo->prepare("SELECT * FROM users WHERE id = ?");',
      "$stmt->execute([$id]);",
      "$user = $stmt->fetch();",
    ),
  },
  {
    id: "php-coalesce",
    language: "php",
    category: "flow",
    difficulty: "easy",
    label: "?? operator",
    description: "null 合体演算子で既定値にする",
    code: j('$page = $_GET["page"] ?? 1;'),
  },
  {
    id: "php-match",
    language: "php",
    category: "flow",
    difficulty: "medium",
    label: "match",
    description: "match 式で点数から成績を決める",
    code: j(
      "$grade = match (true) {",
      '  $score >= 90 => "A",',
      '  $score >= 70 => "B",',
      '  default => "C",',
      "};",
    ),
  },
  {
    id: "php-try",
    language: "php",
    category: "flow",
    difficulty: "hard",
    label: "try / catch",
    description: "トランザクションを失敗時にロールバックする",
    code: j(
      "try {",
      "  $pdo->beginTransaction();",
      "  $stmt->execute([$id]);",
      "  $pdo->commit();",
      "} catch (PDOException $e) {",
      "  $pdo->rollBack();",
      "  throw $e;",
      "}",
    ),
  },

  // ---------------- SQL (idioms) ----------------
  {
    id: "sql-order",
    language: "sql",
    category: "basics",
    difficulty: "easy",
    label: "ORDER BY / LIMIT",
    description: "価格の高い順に上位10件を取る",
    code: j("SELECT name, price FROM products", "ORDER BY price DESC", "LIMIT 10;"),
  },
  {
    id: "sql-like",
    language: "sql",
    category: "basics",
    difficulty: "easy",
    label: "LIKE",
    description: "LIKE でメールのドメインを後方一致検索する",
    code: j("SELECT * FROM users WHERE email LIKE '%@example.com';"),
  },
  {
    id: "sql-create",
    language: "sql",
    category: "basics",
    difficulty: "medium",
    label: "CREATE TABLE",
    description: "制約付きでテーブルを作成する",
    code: j(
      "CREATE TABLE users (",
      "  id INTEGER PRIMARY KEY,",
      "  email TEXT NOT NULL UNIQUE,",
      "  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
      ");",
    ),
  },
  {
    id: "sql-case",
    language: "sql",
    category: "functions",
    difficulty: "medium",
    label: "CASE",
    description: "CASE 式で合計額から顧客ランクを付ける",
    code: j(
      "SELECT name,",
      "  CASE",
      "    WHEN total >= 100 THEN 'vip'",
      "    ELSE 'regular'",
      "  END AS tier",
      "FROM customers;",
    ),
  },
  {
    id: "sql-cte",
    language: "sql",
    category: "functions",
    difficulty: "hard",
    label: "WITH (CTE)",
    description: "CTE で今年の注文を絞ってから集計する",
    code: j(
      "WITH recent AS (",
      "  SELECT * FROM orders WHERE created_at >= '2026-01-01'",
      ")",
      "SELECT user_id, SUM(total) FROM recent GROUP BY user_id;",
    ),
  },
  {
    id: "sql-window",
    language: "sql",
    category: "functions",
    difficulty: "hard",
    label: "Window function",
    description: "ウィンドウ関数でチーム内の順位を付ける",
    code: j(
      "SELECT name, score,",
      "  RANK() OVER (",
      "    PARTITION BY team ORDER BY score DESC",
      "  ) AS team_rank",
      "FROM players;",
    ),
  },
  {
    id: "sql-delete",
    language: "sql",
    category: "flow",
    difficulty: "easy",
    label: "DELETE",
    description: "期限切れのセッションを削除する",
    code: j("DELETE FROM sessions WHERE expires_at < CURRENT_TIMESTAMP;"),
  },
  {
    id: "sql-left-join",
    language: "sql",
    category: "flow",
    difficulty: "medium",
    label: "LEFT JOIN",
    description: "注文が無いユーザーも含めて件数を数える",
    code: j(
      "SELECT u.name, COUNT(o.id) AS orders",
      "FROM users u",
      "LEFT JOIN orders o ON o.user_id = u.id",
      "GROUP BY u.id, u.name;",
    ),
  },
  {
    id: "sql-transaction",
    language: "sql",
    category: "flow",
    difficulty: "hard",
    label: "Transaction",
    description: "トランザクションで残高を安全に振り替える",
    code: j(
      "BEGIN;",
      "UPDATE accounts SET balance = balance - 100 WHERE id = 1;",
      "UPDATE accounts SET balance = balance + 100 WHERE id = 2;",
      "COMMIT;",
    ),
  },
  {
    id: "sql-upsert",
    language: "sql",
    category: "flow",
    difficulty: "hard",
    label: "UPSERT",
    description: "既存の行があれば在庫数を加算する UPSERT",
    code: j(
      "INSERT INTO stock (sku, qty) VALUES ('A1', 5)",
      "ON CONFLICT (sku)",
      "DO UPDATE SET qty = stock.qty + excluded.qty;",
    ),
  },

  // ---------------- Bash (idioms) ----------------
  {
    id: "bash-strict",
    language: "bash",
    category: "basics",
    difficulty: "easy",
    label: "strict mode",
    description: "シバンと厳格モードでスクリプトを始める",
    code: j("#!/usr/bin/env bash", "set -euo pipefail"),
  },
  {
    id: "bash-subst",
    language: "bash",
    category: "basics",
    difficulty: "medium",
    label: "command substitution",
    description: "コマンド置換で日付入りのファイル名を作る",
    code: j("today=$(date +%Y-%m-%d)", 'echo "backup-${today}.tar.gz"'),
  },
  {
    id: "bash-expand",
    language: "bash",
    category: "basics",
    difficulty: "hard",
    label: "parameter expansion",
    description: "パラメータ展開で既定値・ファイル名・拡張子を扱う",
    code: j('port="${PORT:-8080}"', 'file="${path##*/}"', 'echo "${file%.*} on $port"'),
  },
  {
    id: "bash-array",
    language: "bash",
    category: "basics",
    difficulty: "hard",
    label: "array",
    description: "配列の要素数を出して1つずつ処理する",
    code: j(
      "files=(*.log)",
      'echo "${#files[@]} files"',
      'for f in "${files[@]}"; do',
      '  gzip "$f"',
      "done",
    ),
  },
  {
    id: "bash-log",
    language: "bash",
    category: "functions",
    difficulty: "medium",
    label: "local + shift",
    description: "local 変数と shift でログ関数を書く",
    code: j("log() {", '  local level="$1"', "  shift", '  echo "[$level] $*" >&2', "}"),
  },
  {
    id: "bash-trap",
    language: "bash",
    category: "functions",
    difficulty: "hard",
    label: "trap",
    description: "終了時に一時ファイルを必ず消す",
    code: j("tmp=$(mktemp)", "trap 'rm -f \"$tmp\"' EXIT"),
  },
  {
    id: "bash-xargs",
    language: "bash",
    category: "functions",
    difficulty: "hard",
    label: "find + xargs",
    description: "find と xargs で TODO を含むファイルを探す",
    code: j('find . -name "*.ts" -print0 | xargs -0 grep -l "TODO"'),
  },
  {
    id: "bash-while-read",
    language: "bash",
    category: "flow",
    difficulty: "medium",
    label: "while read",
    description: "ファイルを1行ずつ読み込んで処理する",
    code: j("while IFS= read -r line; do", '  echo "> $line"', "done < input.txt"),
  },
  {
    id: "bash-case",
    language: "bash",
    category: "flow",
    difficulty: "medium",
    label: "case",
    description: "case 文でサブコマンドを分岐する",
    code: j(
      'case "$1" in',
      '  start) echo "starting" ;;',
      '  stop) echo "stopping" ;;',
      '  *) echo "usage: $0 start|stop" ;;',
      "esac",
    ),
  },
  {
    id: "bash-wait",
    language: "bash",
    category: "async",
    difficulty: "hard",
    label: "background + wait",
    description: "バックグラウンドで並行実行して wait で待つ",
    code: j(
      'for host in "${hosts[@]}"; do',
      '  ping -c 1 "$host" > /dev/null &',
      "done",
      "wait",
    ),
  },

  // ---------------- CSS (idioms) ----------------
  {
    id: "css-center",
    language: "css",
    category: "basics",
    difficulty: "easy",
    label: "place-items",
    description: "グリッドで上下左右の中央に寄せる",
    code: j(".center {", "  display: grid;", "  place-items: center;", "}"),
  },
  {
    id: "css-hover",
    language: "css",
    category: "basics",
    difficulty: "easy",
    label: ":hover",
    description: "ホバー時に色と下線を変える",
    code: j("a:hover {", "  color: var(--accent);", "  text-decoration: underline;", "}"),
  },
  {
    id: "css-nesting",
    language: "css",
    category: "basics",
    difficulty: "hard",
    label: "nesting",
    description: "ネストで子要素とホバーをまとめて書く",
    code: j(
      ".card {",
      "  padding: 1rem;",
      "  &:hover { box-shadow: 0 4px 12px rgb(0 0 0 / 0.2); }",
      "  & > h2 { margin: 0; }",
      "}",
    ),
  },
  {
    id: "css-has",
    language: "css",
    category: "basics",
    difficulty: "hard",
    label: ":has()",
    description: "不正な入力があるフォームのボタンを無効に見せる",
    code: j(
      "form:has(input:invalid) button {",
      "  opacity: 0.5;",
      "  pointer-events: none;",
      "}",
    ),
  },
  {
    id: "css-clamp",
    language: "css",
    category: "functions",
    difficulty: "medium",
    label: "clamp()",
    description: "clamp で画面幅に応じて文字サイズを変える",
    code: j("h1 {", "  font-size: clamp(1.5rem, 4vw, 3rem);", "}"),
  },
  {
    id: "css-gradient",
    language: "css",
    category: "functions",
    difficulty: "medium",
    label: "linear-gradient",
    description: "斜めの線形グラデーションを背景にする",
    code: j(".hero {", "  background: linear-gradient(135deg, #5cf2ff, #c77dff);", "}"),
  },
  {
    id: "css-auto-fit",
    language: "css",
    category: "functions",
    difficulty: "hard",
    label: "auto-fit grid",
    description: "列数が自動で変わるレスポンシブなグリッド",
    code: j(
      ".gallery {",
      "  display: grid;",
      "  grid-template-columns: repeat(auto-fit, minmax(12rem, 1fr));",
      "  gap: 1rem;",
      "}",
    ),
  },
  {
    id: "css-keyframes",
    language: "css",
    category: "functions",
    difficulty: "hard",
    label: "@keyframes",
    description: "キーフレームで回転し続けるローダー",
    code: j(
      "@keyframes spin {",
      "  to { transform: rotate(360deg); }",
      "}",
      ".loader {",
      "  animation: spin 1s linear infinite;",
      "}",
    ),
  },
  {
    id: "css-dark",
    language: "css",
    category: "flow",
    difficulty: "medium",
    label: "prefers-color-scheme",
    description: "ダークモードのときだけ配色を差し替える",
    code: j(
      "@media (prefers-color-scheme: dark) {",
      "  :root { --bg: #0b0d1a; --fg: #e8ecff; }",
      "}",
    ),
  },
  {
    id: "css-container",
    language: "css",
    category: "flow",
    difficulty: "hard",
    label: "@container",
    description: "コンテナクエリで親の幅に応じて並びを変える",
    code: j(
      ".sidebar { container-type: inline-size; }",
      "@container (min-width: 400px) {",
      "  .card { flex-direction: row; }",
      "}",
    ),
  },

  // ---------------- HTML (idioms) ----------------
  {
    id: "html-heading",
    language: "html",
    category: "basics",
    difficulty: "easy",
    label: "heading + p",
    description: "見出しと強調を含む段落",
    code: j("<h1>Snippet Sprint</h1>", "<p>Type <strong>real</strong> code.</p>"),
  },
  {
    id: "html-head",
    language: "html",
    category: "basics",
    difficulty: "medium",
    label: "document head",
    description: "doctype と head を持つ文書の骨組み",
    code: j(
      "<!doctype html>",
      '<html lang="en">',
      "  <head>",
      '    <meta charset="utf-8" />',
      "    <title>Hello</title>",
      "  </head>",
      "</html>",
    ),
  },
  {
    id: "html-semantic",
    language: "html",
    category: "basics",
    difficulty: "medium",
    label: "landmarks",
    description: "header / nav / main のランドマーク構造",
    code: j(
      "<header>",
      '  <nav aria-label="Main">',
      '    <a href="/">Home</a>',
      "  </nav>",
      "</header>",
      '<main id="content"></main>',
    ),
  },
  {
    id: "html-viewport",
    language: "html",
    category: "basics",
    difficulty: "hard",
    label: "meta viewport",
    description: "モバイル向けの viewport 指定",
    code: j(
      "<meta",
      '  name="viewport"',
      '  content="width=device-width, initial-scale=1"',
      "/>",
    ),
  },
  {
    id: "html-srcset",
    language: "html",
    category: "basics",
    difficulty: "hard",
    label: "responsive img",
    description: "高解像度の代替と遅延読み込みを指定した画像",
    code: j(
      "<img",
      '  src="hero.jpg"',
      '  srcset="hero@2x.jpg 2x"',
      '  alt="Mountain at dawn"',
      '  loading="lazy"',
      "/>",
    ),
  },
  {
    id: "html-table",
    language: "html",
    category: "basics",
    difficulty: "hard",
    label: "table",
    description: "見出しセル付きの表",
    code: j(
      "<table>",
      "  <tr>",
      '    <th scope="col">Name</th>',
      '    <th scope="col">Score</th>',
      "  </tr>",
      "  <tr>",
      "    <td>Ada</td>",
      "    <td>98</td>",
      "  </tr>",
      "</table>",
    ),
  },
  {
    id: "html-button",
    language: "html",
    category: "functions",
    difficulty: "easy",
    label: "button",
    description: "無効状態の送信ボタン",
    code: j('<button type="submit" disabled>Save</button>'),
  },
  {
    id: "html-assets",
    language: "html",
    category: "functions",
    difficulty: "medium",
    label: "link + script",
    description: "スタイルシートとモジュールスクリプトを読み込む",
    code: j(
      '<link rel="stylesheet" href="/styles.css" />',
      '<script type="module" src="/main.js"></script>',
    ),
  },
  {
    id: "html-select",
    language: "html",
    category: "functions",
    difficulty: "medium",
    label: "select",
    description: "既定の選択肢を持つセレクトボックス",
    code: j(
      '<select name="lang">',
      '  <option value="ts" selected>TypeScript</option>',
      '  <option value="go">Go</option>',
      "</select>",
    ),
  },
  {
    id: "html-form",
    language: "html",
    category: "functions",
    difficulty: "hard",
    label: "form",
    description: "必須入力と送信ボタンを持つフォーム",
    code: j(
      '<form action="/login" method="post">',
      '  <input type="password" name="password" required />',
      '  <button type="submit">Sign in</button>',
      "</form>",
    ),
  },

  // ---------------- C ----------------
  {
    id: "c-hello",
    language: "c",
    category: "basics",
    difficulty: "easy",
    label: "printf",
    description: "標準出力に文字列を表示する",
    code: j('printf("hello, world\\n");'),
  },
  {
    id: "c-define",
    language: "c",
    category: "basics",
    difficulty: "easy",
    label: "#define",
    description: "マクロ定数で配列のサイズを決める",
    code: j("#define MAX_USERS 64", "static int ids[MAX_USERS];"),
  },
  {
    id: "c-main",
    language: "c",
    category: "basics",
    difficulty: "medium",
    label: "main",
    description: "ヘッダを読み込む最小のプログラム",
    code: j(
      "#include <stdio.h>",
      "int main(void) {",
      '  puts("hello, world");',
      "  return 0;",
      "}",
    ),
  },
  {
    id: "c-struct",
    language: "c",
    category: "basics",
    difficulty: "medium",
    label: "typedef struct",
    description: "typedef で構造体に型名を付ける",
    code: j("typedef struct {", "  double x;", "  double y;", "} Point;"),
  },
  {
    id: "c-func",
    language: "c",
    category: "functions",
    difficulty: "easy",
    label: "function",
    description: "三項演算子で大きい方を返す関数",
    code: j("int max(int a, int b) {", "  return a > b ? a : b;", "}"),
  },
  {
    id: "c-swap",
    language: "c",
    category: "functions",
    difficulty: "medium",
    label: "pointer swap",
    description: "ポインタ経由で2つの値を入れ替える",
    code: j(
      "void swap(int *a, int *b) {",
      "  int tmp = *a;",
      "  *a = *b;",
      "  *b = tmp;",
      "}",
    ),
  },
  {
    id: "c-qsort",
    language: "c",
    category: "functions",
    difficulty: "hard",
    label: "qsort comparator",
    description: "qsort に渡す比較関数（オーバーフローしない書き方）",
    code: j(
      "int cmp(const void *a, const void *b) {",
      "  int x = *(const int *)a, y = *(const int *)b;",
      "  return (x > y) - (x < y);",
      "}",
    ),
  },
  {
    id: "c-for",
    language: "c",
    category: "flow",
    difficulty: "easy",
    label: "for loop",
    description: "配列の要素を for ループで合計する",
    code: j("for (int i = 0; i < n; i++) {", "  sum += a[i];", "}"),
  },
  {
    id: "c-switch",
    language: "c",
    category: "flow",
    difficulty: "medium",
    label: "switch",
    description: "演算子の文字で switch して計算する",
    code: j(
      "switch (op) {",
      "  case '+': return a + b;",
      "  case '-': return a - b;",
      "  default: return 0;",
      "}",
    ),
  },
  {
    id: "c-malloc",
    language: "c",
    category: "flow",
    difficulty: "hard",
    label: "malloc / free",
    description: "動的に確保して失敗を確認し解放する",
    code: j(
      "int *buf = malloc(n * sizeof *buf);",
      "if (buf == NULL) {",
      "  return -1;",
      "}",
      "free(buf);",
    ),
  },
  {
    id: "c-file",
    language: "c",
    category: "flow",
    difficulty: "hard",
    label: "fopen",
    description: "ファイルを開き失敗時はエラーを表示する",
    code: j(
      'FILE *fp = fopen(path, "r");',
      "if (fp == NULL) {",
      '  perror("fopen");',
      "  return 1;",
      "}",
      "fclose(fp);",
    ),
  },
  {
    id: "c-pthread",
    language: "c",
    category: "async",
    difficulty: "hard",
    label: "pthread",
    description: "スレッドを起動して終了を待つ",
    code: j(
      "pthread_t tid;",
      "pthread_create(&tid, NULL, worker, &arg);",
      "pthread_join(tid, NULL);",
    ),
  },
];
