import type { Snippet } from "./types.js";

// Join rows into a single `\n`-delimited string. Rows are written as
// single-quoted strings so inner backticks and ${...} stay literal.
const j = (...rows: string[]): string => rows.join("\n");

export const CODE_SNIPPETS: Snippet[] = [
  // ---------------- TypeScript / JavaScript ----------------
  {
    id: "ts-const",
    language: "ts",
    category: "basics",
    difficulty: "easy",
    label: "const & log",
    description: "文字列を定数に入れてコンソール出力する",
    code: j('const greeting = "hello, world";', "console.log(greeting);"),
  },
  {
    id: "ts-ternary",
    language: "ts",
    category: "flow",
    difficulty: "easy",
    label: "Ternary",
    description: "三項演算子で条件によって値を選ぶ",
    code: j('const label = ok ? "yes" : "no";'),
  },
  {
    id: "ts-arrow",
    language: "ts",
    category: "functions",
    difficulty: "easy",
    label: "Arrow fn",
    description: "2つの数値を受け取り和を返すアロー関数",
    code: j("const sum = (a: number, b: number): number => a + b;"),
  },
  {
    id: "ts-chain",
    language: "ts",
    category: "functions",
    difficulty: "medium",
    label: "filter / map",
    description: "偶数だけ絞り込んで2倍にするメソッドチェーン",
    code: j(
      "const doubled = nums",
      "  .filter((n) => n % 2 === 0)",
      "  .map((n) => n * 2);",
    ),
  },
  {
    id: "ts-interface",
    language: "ts",
    category: "basics",
    difficulty: "medium",
    label: "Interface",
    description: "オブジェクトの形を表す interface 定義",
    code: j(
      "interface User {",
      "  id: number;",
      "  name: string;",
      "  active?: boolean;",
      "}",
    ),
  },
  {
    id: "ts-async",
    language: "ts",
    category: "async",
    difficulty: "medium",
    label: "async / await",
    description: "URL を非同期に取得して JSON を返す",
    code: j(
      "async function load(url: string) {",
      "  const res = await fetch(url);",
      "  return res.json();",
      "}",
    ),
  },
  {
    id: "ts-guard",
    language: "ts",
    category: "flow",
    difficulty: "hard",
    label: "Guard clause",
    description: "権限を判定して許可するか例外を投げる",
    code: j(
      'if (user?.role === "admin" && !user.banned) {',
      "  grantAccess();",
      "} else {",
      '  throw new Error("denied");',
      "}",
    ),
  },
  {
    id: "ts-react",
    language: "ts",
    category: "functions",
    difficulty: "hard",
    label: "React hooks",
    description: "state とドキュメントタイトルを同期する hooks",
    code: j(
      "const [count, setCount] = useState(0);",
      "useEffect(() => {",
      "  document.title = `count: ${count}`;",
      "}, [count]);",
    ),
  },

  // ---------------- Python ----------------
  {
    id: "py-print",
    language: "py",
    category: "basics",
    difficulty: "easy",
    label: "print",
    description: "文字列を標準出力する",
    code: j('print("hello, world")'),
  },
  {
    id: "py-fstring",
    language: "py",
    category: "basics",
    difficulty: "easy",
    label: "f-string",
    description: "f-string で変数を埋め込んで出力する",
    code: j('name = "Ada"', 'print(f"hello, {name}!")'),
  },
  {
    id: "py-def",
    language: "py",
    category: "functions",
    difficulty: "easy",
    label: "def",
    description: "2つの引数を足して返す関数定義",
    code: j("def add(a, b):", "    return a + b"),
  },
  {
    id: "py-comp",
    language: "py",
    category: "functions",
    difficulty: "medium",
    label: "Comprehension",
    description: "内包表記で偶数の二乗リストを作る",
    code: j("squares = [x * x for x in range(10) if x % 2 == 0]"),
  },
  {
    id: "py-dict",
    language: "py",
    category: "basics",
    difficulty: "medium",
    label: "Dict literal",
    description: "辞書リテラルで設定値をまとめる",
    code: j("config = {", '    "debug": True,', '    "retries": 3,', "}"),
  },
  {
    id: "py-with",
    language: "py",
    category: "flow",
    difficulty: "medium",
    label: "with / for",
    description: "ファイルを開いて1行ずつ処理する",
    code: j(
      'with open("data.txt") as f:',
      "    for line in f:",
      "        print(line.strip())",
    ),
  },
  {
    id: "py-try",
    language: "py",
    category: "flow",
    difficulty: "hard",
    label: "try / except",
    description: "例外を捕まえて既定値にフォールバックする",
    code: j(
      "try:",
      "    value = int(raw)",
      "except ValueError:",
      "    value = 0",
    ),
  },
  {
    id: "py-decorator",
    language: "py",
    category: "functions",
    difficulty: "hard",
    label: "Decorator",
    description: "デコレータで URL ルーティングを定義する",
    code: j(
      '@app.route("/users/<int:id>")',
      "def get_user(id):",
      "    return jsonify(db.get(id))",
    ),
  },

  // ---------------- Go ----------------
  {
    id: "go-hello",
    language: "go",
    category: "basics",
    difficulty: "easy",
    label: "Println",
    description: "標準出力に文字列を表示する",
    code: j('fmt.Println("hello, world")'),
  },
  {
    id: "go-func",
    language: "go",
    category: "functions",
    difficulty: "easy",
    label: "func",
    description: "2つの整数を足して返す関数",
    code: j("func add(a, b int) int {", "  return a + b", "}"),
  },
  {
    id: "go-struct",
    language: "go",
    category: "basics",
    difficulty: "medium",
    label: "struct",
    description: "座標を表す構造体の定義",
    code: j("type Point struct {", "  X int", "  Y int", "}"),
  },
  {
    id: "go-range",
    language: "go",
    category: "functions",
    difficulty: "medium",
    label: "for range",
    description: "スライスを range で添字付きに反復する",
    code: j(
      "nums := []int{1, 2, 3, 4}",
      "for i, n := range nums {",
      '  fmt.Printf("%d: %d\\n", i, n)',
      "}",
    ),
  },
  {
    id: "go-err",
    language: "go",
    category: "flow",
    difficulty: "hard",
    label: "if err != nil",
    description: "ファイル読込のエラーを早期 return する",
    code: j(
      "data, err := os.ReadFile(path)",
      "if err != nil {",
      "  return nil, err",
      "}",
    ),
  },
  {
    id: "go-goroutine",
    language: "go",
    category: "async",
    difficulty: "hard",
    label: "goroutine",
    description: "goroutine で計算しチャネルで受け取る",
    code: j("go func() {", "  ch <- compute()", "}()", "result := <-ch"),
  },

  // ---------------- Rust ----------------
  {
    id: "rust-hello",
    language: "rust",
    category: "basics",
    difficulty: "easy",
    label: "println!",
    description: "マクロで文字列を表示する",
    code: j('println!("hello, world");'),
  },
  {
    id: "rust-loop",
    language: "rust",
    category: "flow",
    difficulty: "easy",
    label: "for range",
    description: "1〜10 を合計する for ループ",
    code: j("let mut total: u32 = 0;", "for n in 1..=10 {", "  total += n;", "}"),
  },
  {
    id: "rust-fn",
    language: "rust",
    category: "functions",
    difficulty: "medium",
    label: "fn",
    description: "整数を2乗して返す関数",
    code: j("fn square(x: i32) -> i32 {", "  x * x", "}"),
  },
  {
    id: "rust-struct",
    language: "rust",
    category: "basics",
    difficulty: "medium",
    label: "struct",
    description: "名前と年齢を持つ構造体",
    code: j("struct User {", "  name: String,", "  age: u8,", "}"),
  },
  {
    id: "rust-match",
    language: "rust",
    category: "flow",
    difficulty: "medium",
    label: "match",
    description: "Result を match で成功/失敗に分岐する",
    code: j(
      "match result {",
      '  Ok(v) => println!("{v}"),',
      '  Err(e) => eprintln!("{e}"),',
      "}",
    ),
  },
  {
    id: "rust-iter",
    language: "rust",
    category: "functions",
    difficulty: "hard",
    label: "iterator chain",
    description: "イテレータで正の数だけ合計する",
    code: j(
      "let sum: i32 = nums",
      "  .iter()",
      "  .filter(|&&n| n > 0)",
      "  .sum();",
    ),
  },
  {
    id: "rust-option",
    language: "rust",
    category: "flow",
    difficulty: "hard",
    label: "unwrap_or_else",
    description: "None なら既定の文字列を返す",
    code: j('let name = user.name.unwrap_or_else(|| "anon".to_string());'),
  },

  // ---------------- Java ----------------
  {
    id: "java-hello",
    language: "java",
    category: "basics",
    difficulty: "easy",
    label: "println",
    description: "標準出力に文字列を表示する",
    code: j('System.out.println("hello, world");'),
  },
  {
    id: "java-loop",
    language: "java",
    category: "flow",
    difficulty: "easy",
    label: "for loop",
    description: "0〜9 を順に出力する for ループ",
    code: j("for (int i = 0; i < 10; i++) {", "  System.out.println(i);", "}"),
  },
  {
    id: "java-stream",
    language: "java",
    category: "functions",
    difficulty: "medium",
    label: "Stream",
    description: "Stream で偶数だけ集める",
    code: j(
      "List<Integer> evens = nums.stream()",
      "  .filter(n -> n % 2 == 0)",
      "  .toList();",
    ),
  },

  // ---------------- C++ ----------------
  {
    id: "cpp-hello",
    language: "cpp",
    category: "basics",
    difficulty: "easy",
    label: "cout",
    description: "標準出力に文字列を流す",
    code: j('std::cout << "hello, world" << std::endl;'),
  },
  {
    id: "cpp-func",
    language: "cpp",
    category: "functions",
    difficulty: "easy",
    label: "function",
    description: "2つの整数を足して返す関数",
    code: j("int add(int a, int b) {", "  return a + b;", "}"),
  },
  {
    id: "cpp-vector",
    language: "cpp",
    category: "flow",
    difficulty: "medium",
    label: "range for",
    description: "vector を範囲 for で1要素ずつ出力",
    code: j(
      "std::vector<int> nums = {1, 2, 3};",
      "for (int n : nums) {",
      '  std::cout << n << "\\n";',
      "}",
    ),
  },

  // ---------------- SQL ----------------
  {
    id: "sql-select",
    language: "sql",
    category: "basics",
    difficulty: "easy",
    label: "SELECT",
    description: "条件付きで列を取り出す基本のSELECT",
    code: j("SELECT id, name FROM users WHERE active = true;"),
  },
  {
    id: "sql-join",
    language: "sql",
    category: "flow",
    difficulty: "medium",
    label: "JOIN",
    description: "2つのテーブルを結合して取得",
    code: j(
      "SELECT u.name, o.total",
      "FROM users u",
      "JOIN orders o ON o.user_id = u.id;",
    ),
  },
  {
    id: "sql-group",
    language: "sql",
    category: "functions",
    difficulty: "medium",
    label: "GROUP BY",
    description: "カテゴリ別に集計して件数で絞る",
    code: j(
      "SELECT category, COUNT(*) AS n",
      "FROM products",
      "GROUP BY category",
      "HAVING COUNT(*) > 5;",
    ),
  },

  // ---------------- TypeScript / JavaScript (more) ----------------
  {
    id: "ts-destructure",
    language: "ts",
    category: "basics",
    difficulty: "easy",
    label: "Destructuring",
    description: "分割代入で必要な値と残りを取り出す",
    code: j("const { id, name, ...rest } = user;"),
  },
  {
    id: "ts-switch",
    language: "ts",
    category: "flow",
    difficulty: "medium",
    label: "switch",
    description: "switch 文で状態に応じて分岐する",
    code: j(
      "switch (status) {",
      '  case "ok":',
      "    return 200;",
      "  default:",
      "    return 500;",
      "}",
    ),
  },
  {
    id: "ts-promise-all",
    language: "ts",
    category: "async",
    difficulty: "medium",
    label: "Promise.all",
    description: "複数の非同期処理を並行に待つ",
    code: j(
      "const users = await Promise.all(",
      "  ids.map((id) => fetchUser(id)),",
      ");",
    ),
  },
  {
    id: "ts-generic",
    language: "ts",
    category: "functions",
    difficulty: "hard",
    label: "Generics",
    description: "ジェネリクスで型を保ったまま先頭要素を返す",
    code: j(
      "function first<T>(arr: T[]): T | undefined {",
      "  return arr[0];",
      "}",
    ),
  },

  // ---------------- Python (more) ----------------
  {
    id: "py-enumerate",
    language: "py",
    category: "functions",
    difficulty: "easy",
    label: "enumerate",
    description: "enumerate で添字付きに反復する",
    code: j("for i, item in enumerate(items):", "    print(i, item)"),
  },
  {
    id: "py-class",
    language: "py",
    category: "basics",
    difficulty: "medium",
    label: "class",
    description: "コンストラクタを持つクラス定義",
    code: j(
      "class Point:",
      "    def __init__(self, x, y):",
      "        self.x = x",
      "        self.y = y",
    ),
  },
  {
    id: "py-async",
    language: "py",
    category: "async",
    difficulty: "medium",
    label: "async / await",
    description: "非同期にHTTP取得してJSONを返す",
    code: j(
      "async def fetch(url):",
      "    async with session.get(url) as r:",
      "        return await r.json()",
    ),
  },

  // ---------------- Go (more) ----------------
  {
    id: "go-map",
    language: "go",
    category: "basics",
    difficulty: "medium",
    label: "map count",
    description: "map で単語の出現回数を数える",
    code: j(
      "counts := map[string]int{}",
      "for _, w := range words {",
      "  counts[w]++",
      "}",
    ),
  },
  {
    id: "go-defer",
    language: "go",
    category: "flow",
    difficulty: "medium",
    label: "defer close",
    description: "defer でファイルを確実に閉じる",
    code: j(
      "f, err := os.Open(path)",
      "if err != nil {",
      "  return err",
      "}",
      "defer f.Close()",
    ),
  },
  {
    id: "go-interface",
    language: "go",
    category: "basics",
    difficulty: "medium",
    label: "interface",
    description: "メソッドを定義するインターフェース",
    code: j("type Stringer interface {", "  String() string", "}"),
  },

  // ---------------- Rust (more) ----------------
  {
    id: "rust-vec",
    language: "rust",
    category: "basics",
    difficulty: "easy",
    label: "Vec",
    description: "可変ベクタに要素を追加する",
    code: j("let mut v = vec![1, 2, 3];", "v.push(4);"),
  },
  {
    id: "rust-iflet",
    language: "rust",
    category: "flow",
    difficulty: "medium",
    label: "if let",
    description: "if let で Some のときだけ取り出す",
    code: j("if let Some(x) = maybe {", '  println!("{x}");', "}"),
  },
  {
    id: "rust-trait",
    language: "rust",
    category: "basics",
    difficulty: "hard",
    label: "trait",
    description: "面積を返すトレイト定義",
    code: j("trait Shape {", "  fn area(&self) -> f64;", "}"),
  },

  // ---------------- Java (more) ----------------
  {
    id: "java-class",
    language: "java",
    category: "basics",
    difficulty: "medium",
    label: "class",
    description: "フィールドとゲッターを持つクラス",
    code: j(
      "public class User {",
      "  private String name;",
      "  public String getName() {",
      "    return name;",
      "  }",
      "}",
    ),
  },
  {
    id: "java-map",
    language: "java",
    category: "functions",
    difficulty: "medium",
    label: "Map merge",
    description: "Map.merge で出現回数を加算する",
    code: j(
      "Map<String, Integer> counts = new HashMap<>();",
      "counts.merge(word, 1, Integer::sum);",
    ),
  },
  {
    id: "java-try",
    language: "java",
    category: "flow",
    difficulty: "medium",
    label: "try / catch",
    description: "例外を捕捉してログ出力する",
    code: j(
      "try {",
      "  process();",
      "} catch (IOException e) {",
      "  log.error(e);",
      "}",
    ),
  },

  // ---------------- C++ (more) ----------------
  {
    id: "cpp-class",
    language: "cpp",
    category: "basics",
    difficulty: "medium",
    label: "class",
    description: "公開メンバを持つクラス",
    code: j("class Point {", "public:", "  int x, y;", "};"),
  },
  {
    id: "cpp-auto",
    language: "cpp",
    category: "functions",
    difficulty: "medium",
    label: "auto + range for",
    description: "auto と範囲 for で合計を取る",
    code: j("auto sum = 0;", "for (auto n : nums) sum += n;"),
  },
  {
    id: "cpp-smartptr",
    language: "cpp",
    category: "basics",
    difficulty: "hard",
    label: "unique_ptr",
    description: "スマートポインタを生成して参照する",
    code: j(
      "auto p = std::make_unique<Node>(1);",
      "std::cout << p->value;",
    ),
  },

  // ---------------- SQL (more) ----------------
  {
    id: "sql-insert",
    language: "sql",
    category: "basics",
    difficulty: "easy",
    label: "INSERT",
    description: "テーブルに行を追加する",
    code: j("INSERT INTO users (name, email) VALUES ('Ada', 'ada@x.io');"),
  },
  {
    id: "sql-update",
    language: "sql",
    category: "flow",
    difficulty: "easy",
    label: "UPDATE",
    description: "条件に一致する行を更新する",
    code: j("UPDATE users SET active = false WHERE last_login < '2025-01-01';"),
  },
  {
    id: "sql-subquery",
    language: "sql",
    category: "functions",
    difficulty: "hard",
    label: "Subquery",
    description: "サブクエリで条件に合うユーザーを抽出",
    code: j(
      "SELECT name FROM users",
      "WHERE id IN (SELECT user_id FROM orders WHERE total > 100);",
    ),
  },

  // ---------------- Bash ----------------
  {
    id: "bash-vars",
    language: "bash",
    category: "basics",
    difficulty: "easy",
    label: "variables",
    description: "変数に代入して展開する",
    code: j('name="world"', 'echo "hello, $name"'),
  },
  {
    id: "bash-loop",
    language: "bash",
    category: "flow",
    difficulty: "easy",
    label: "for loop",
    description: "ファイルをループで処理する",
    code: j("for f in *.txt; do", '  echo "$f"', "done"),
  },
  {
    id: "bash-pipe",
    language: "bash",
    category: "functions",
    difficulty: "medium",
    label: "pipe",
    description: "パイプで 404 行を数える",
    code: j("cat access.log | grep 404 | wc -l"),
  },
  {
    id: "bash-if",
    language: "bash",
    category: "flow",
    difficulty: "medium",
    label: "if test",
    description: "ファイルの存在を判定する",
    code: j('if [ -f "$1" ]; then', '  echo "exists"', "fi"),
  },
  {
    id: "bash-func",
    language: "bash",
    category: "functions",
    difficulty: "medium",
    label: "function",
    description: "引数を受け取る関数を定義する",
    code: j("greet() {", '  echo "hi, $1"', "}"),
  },

  // ---------------- CSS ----------------
  {
    id: "css-flex",
    language: "css",
    category: "basics",
    difficulty: "easy",
    label: "flexbox",
    description: "フレックスボックスで横並び+間隔",
    code: j(".row {", "  display: flex;", "  gap: 8px;", "}"),
  },
  {
    id: "css-var",
    language: "css",
    category: "basics",
    difficulty: "easy",
    label: "custom property",
    description: "カスタムプロパティ（CSS変数）を定義",
    code: j(":root {", "  --accent: #5cf2ff;", "}"),
  },
  {
    id: "css-grid",
    language: "css",
    category: "basics",
    difficulty: "medium",
    label: "grid",
    description: "グリッドで3カラム等分レイアウト",
    code: j(
      ".grid {",
      "  display: grid;",
      "  grid-template-columns: repeat(3, 1fr);",
      "}",
    ),
  },
  {
    id: "css-media",
    language: "css",
    category: "flow",
    difficulty: "medium",
    label: "media query",
    description: "メディアクエリで縦並びに切替",
    code: j(
      "@media (max-width: 600px) {",
      "  .row { flex-direction: column; }",
      "}",
    ),
  },
  {
    id: "css-transition",
    language: "css",
    category: "functions",
    difficulty: "medium",
    label: "transition",
    description: "ホバー時のトランジションを定義",
    code: j(".btn {", "  transition: transform 0.2s ease;", "}"),
  },

  // ---------------- C# ----------------
  {
    id: "csharp-write",
    language: "csharp",
    category: "basics",
    difficulty: "easy",
    label: "WriteLine",
    description: "コンソールに文字列を出力する",
    code: j('Console.WriteLine("hello, world");'),
  },
  {
    id: "csharp-linq",
    language: "csharp",
    category: "functions",
    difficulty: "medium",
    label: "LINQ",
    description: "LINQ で偶数だけ抽出する",
    code: j("var evens = nums.Where(n => n % 2 == 0).ToList();"),
  },
  {
    id: "csharp-prop",
    language: "csharp",
    category: "basics",
    difficulty: "medium",
    label: "auto-property",
    description: "自動プロパティを持つクラス",
    code: j(
      "public class User {",
      "  public string Name { get; set; }",
      "}",
    ),
  },
  {
    id: "csharp-foreach",
    language: "csharp",
    category: "flow",
    difficulty: "easy",
    label: "foreach",
    description: "コレクションを foreach で走査する",
    code: j(
      "foreach (var item in items) {",
      "  Console.WriteLine(item);",
      "}",
    ),
  },

  // ---------------- Swift ----------------
  {
    id: "swift-print",
    language: "swift",
    category: "basics",
    difficulty: "easy",
    label: "print",
    description: "標準出力に文字列を表示する",
    code: j('print("hello, world")'),
  },
  {
    id: "swift-map",
    language: "swift",
    category: "functions",
    difficulty: "easy",
    label: "map",
    description: "クロージャ省略記法で2倍にする",
    code: j("let nums = [1, 2, 3]", "let doubled = nums.map { $0 * 2 }"),
  },
  {
    id: "swift-func",
    language: "swift",
    category: "functions",
    difficulty: "medium",
    label: "func",
    description: "2つの整数を足して返す関数",
    code: j("func add(_ a: Int, _ b: Int) -> Int {", "  a + b", "}"),
  },
  {
    id: "swift-guard",
    language: "swift",
    category: "flow",
    difficulty: "medium",
    label: "guard let",
    description: "guard let で早期 return する",
    code: j("guard let name = user.name else {", "  return", "}"),
  },

  // ---------------- Kotlin ----------------
  {
    id: "kotlin-fun",
    language: "kotlin",
    category: "functions",
    difficulty: "easy",
    label: "fun (expression)",
    description: "式本体の関数定義",
    code: j("fun add(a: Int, b: Int) = a + b"),
  },
  {
    id: "kotlin-val",
    language: "kotlin",
    category: "basics",
    difficulty: "easy",
    label: "val + sum",
    description: "リストを作って合計する",
    code: j("val nums = listOf(1, 2, 3)", "val sum = nums.sum()"),
  },
  {
    id: "kotlin-data",
    language: "kotlin",
    category: "basics",
    difficulty: "medium",
    label: "data class",
    description: "データクラスを1行で定義",
    code: j("data class User(val id: Int, val name: String)"),
  },
  {
    id: "kotlin-when",
    language: "kotlin",
    category: "flow",
    difficulty: "medium",
    label: "when",
    description: "when 式で値によって分岐する",
    code: j("when (status) {", '  200 -> "ok"', '  else -> "error"', "}"),
  },

  // ---------------- Ruby ----------------
  {
    id: "ruby-puts",
    language: "ruby",
    category: "basics",
    difficulty: "easy",
    label: "puts",
    description: "標準出力に文字列を表示する",
    code: j('puts "hello, world"'),
  },
  {
    id: "ruby-each",
    language: "ruby",
    category: "functions",
    difficulty: "easy",
    label: "each block",
    description: "ブロックで配列を反復する",
    code: j("[1, 2, 3].each { |n| puts n }"),
  },
  {
    id: "ruby-method",
    language: "ruby",
    category: "functions",
    difficulty: "medium",
    label: "method",
    description: "文字列補間で挨拶を返すメソッド",
    code: j("def greet(name)", '  "hi, #{name}"', "end"),
  },
  {
    id: "ruby-map",
    language: "ruby",
    category: "functions",
    difficulty: "medium",
    label: "map + select",
    description: "select と map をチェーンする",
    code: j("evens = nums.select { |n| n.even? }.map { |n| n * 2 }"),
  },

  // ---------------- PHP ----------------
  {
    id: "php-echo",
    language: "php",
    category: "basics",
    difficulty: "easy",
    label: "echo",
    description: "文字列を出力する",
    code: j('echo "hello, world";'),
  },
  {
    id: "php-array",
    language: "php",
    category: "functions",
    difficulty: "medium",
    label: "array_filter",
    description: "アロー関数で正の数だけ残す",
    code: j("$nums = array_filter($xs, fn($n) => $n > 0);"),
  },
  {
    id: "php-foreach",
    language: "php",
    category: "flow",
    difficulty: "medium",
    label: "foreach",
    description: "オブジェクト配列を foreach で走査",
    code: j("foreach ($users as $user) {", "  echo $user->name;", "}"),
  },

  // ---------------- HTML ----------------
  {
    id: "html-link",
    language: "html",
    category: "basics",
    difficulty: "easy",
    label: "anchor",
    description: "リンク（アンカー）要素",
    code: j('<a href="/about">About</a>'),
  },
  {
    id: "html-img",
    language: "html",
    category: "basics",
    difficulty: "easy",
    label: "img",
    description: "alt 付きの画像要素",
    code: j('<img src="logo.png" alt="logo" />'),
  },
  {
    id: "html-list",
    language: "html",
    category: "basics",
    difficulty: "medium",
    label: "list",
    description: "箇条書きリスト",
    code: j("<ul>", "  <li>one</li>", "  <li>two</li>", "</ul>"),
  },
  {
    id: "html-input",
    language: "html",
    category: "functions",
    difficulty: "medium",
    label: "labeled input",
    description: "ラベル付きの入力フォーム",
    code: j(
      "<label>",
      "  Email",
      '  <input type="email" name="email" />',
      "</label>",
    ),
  },
];
